Repository qiskit-community/qiskit-nature, pull requests merged in 2021-05, with the labels that each got.

#170 Re-enable TwoQubitReduction + UCCSD test
  test/algorithms/ground_state_solvers/test_advanced_ucc_variants.py
Labels: run_slow

#176 Insert actual path to source when generating docs
  docs/conf.py
Labels: type: documentation

#177 Add git blame ignore file
  .git-blame-ignore-revs
  CONTRIBUTING.md
Labels: type: qa

#178 Fix sphinx CI Error
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: automerge, priority: high, stable backport potential, type: ci

#181 [Stable] Fix sphinx CI Error (#178)
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: type: ci

#187 Pin Sphinx version below 4.0.0
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  requirements-dev.txt
Labels: stable backport potential, type: ci

#189 [Stable] Pin Sphinx version below 4.0.0 (#187)
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  requirements-dev.txt
Labels: priority: high, type: documentation

#161 Hermiticity checks for SecondQuantizedOps
  qiskit_nature/operators/second_quantization/second_quantized_op.py
  releasenotes/notes/add-hermiticity-checks-secondquantizedops-c9b28597bb9ec6a0.yaml
  test/operators/second_quantization/test_fermionic_op.py
  test/operators/second_quantization/test_spin_op.py
  test/operators/second_quantization/test_vibrational_op.py
Labels: automerge

#191 Add GettingStarted for Qiskit Nature
  docs/conf.py
  docs/custom_directives.py
  docs/getting_started.rst
  docs/index.rst
  requirements-dev.txt
Labels: type: documentation

#193 Fix #192
  qiskit_nature/problems/second_quantization/electronic/electronic_structure_problem.py
  releasenotes/notes/fix-incompatibility-of-freeze-core-and-z2symmetry-1b5caa71986abaee.yaml
  test/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
Labels: Changelog: Bugfix, run_slow, stable backport potential

#194 [Stable] Add GettingStarted for Qiskit Nature (#191)
  docs/conf.py
  docs/custom_directives.py
  docs/getting_started.rst
  docs/index.rst
  requirements-dev.txt
Labels: type: documentation

#202 Apply spell check to tutorials
  Makefile
  docs/Makefile
  docs/conf.py
  docs/spelling_wordlist.txt
  docs/tutorials/05_Sampling_potential_energy_surfaces.ipynb
  docs/tutorials/07_leveraging_qiskit_runtime.ipynb
  requirements-dev.txt
Labels: automerge

#206 Merge spelling dictionaries into one single .pylintdict file
  .pylintdict
  docs/conf.py
  docs/lowercase_filter.py
  docs/spelling_wordlist.txt
  tools/generate_spell_dict.py
Labels: type: documentation

#205 Update pyscfdriver.py links
  qiskit_nature/drivers/pyscfd/pyscfdriver.py
Labels: automerge

#209 Create separate make rule to clean docs _build/stubs folders
  .github/workflows/main.yml
  Makefile
  docs/Makefile
Labels: type: ci, type: documentation

#211 Rename Aer qasm_simulator to aer_simulator in tests
  test/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
Labels: run_slow, type: bug

#212 Remove Backend Deprecate Messages
  README.md
  docs/tutorials/03_ground_state_solvers.ipynb
  docs/tutorials/04_excited_states_solvers.ipynb
  docs/tutorials/05_Sampling_potential_energy_surfaces.ipynb
  docs/tutorials/06_calculating_thermodynamic_observables.ipynb
  test/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
  test/test_readme_sample.py
Labels: type: enhancement

#208 particle numbers and magnetization, wrong order in the doc
  qiskit_nature/problems/second_quantization/electronic/electronic_structure_problem.py
Labels: automerge, type: documentation

#217 Fix to random unit test method failure
  test/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
Labels: type: bug
