Repository qiskit-community/qiskit-nature, pull requests merged in 2021-07, with the labels that each got.

#256 Preparing docs & tutorials for translations
  .github/workflows/deploy-docs.yml
  docs/_templates/versions.html
  docs/conf.py
  docs/versionutils.py
  tools/deploy_translatable_strings.sh
  tools/github_poBranch_update_key.enc
  tox.ini
Labels: type: documentation

#257 [Stable] Preparing docs & tutorials for translations (#256)
  .github/workflows/deploy-docs.yml
  constraints.txt
  docs/_templates/versions.html
  docs/conf.py
  docs/versionutils.py
  qiskit_nature/algorithms/excited_states_solvers/qeom.py
  qiskit_nature/algorithms/pes_samplers/potentials/harmonic_potential.py
  qiskit_nature/drivers/bosonic_bases/harmonic_basis.py
  qiskit_nature/drivers/fcidumpd/dumper.py
  qiskit_nature/drivers/fcidumpd/fcidumpdriver.py
  qiskit_nature/drivers/fcidumpd/parser.py
  qiskit_nature/results/vibrational_structure_result.py
  requirements-dev.txt
  requirements.txt
  test/algorithms/excited_state_solvers/test_bosonic_esc_calculation.py
  test/algorithms/excited_state_solvers/test_excited_states_solvers.py
  tools/deploy_translatable_strings.sh
  tools/github_poBranch_update_key.enc
  tox.ini
Labels: type: documentation

#266 Deprecated Location: Improve Windows compatibility (pathlib) for psi4
  qiskit_nature/drivers/psi4d/psi4driver.py
Labels: type: bug

#268 Pin networkx
  requirements-dev.txt
Labels: priority: critical, stable backport potential, type: bug

#267 Updating the translation deploy script
  docs/conf.py
  tools/deploy_translatable_strings.sh
Labels: stable backport potential

#276 Streamline CI
  .github/workflows/main.yml
Labels: type: ci, type: enhancement

#277 [Stable] Streamline CI (#276)
  .github/workflows/main.yml
Labels: type: ci, type: enhancement

#281 Add Windows/Mac CI support
  .github/actions/install-libraries/action.yml
  .github/actions/install-main-dependencies/action.yml
  .github/actions/install-nature/action.yml
  .github/actions/install-psi4/action.yml
  .github/actions/run-tests/action.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  qiskit_nature/drivers/pyscfd/pyscfdriver.py
  qiskit_nature/drivers/second_quantization/pyscfd/pyscfdriver.py
  test/__init__.py
  test/algorithms/excited_state_solvers/eigensolver_factories/test_numpy_eigensolver_factory.py
  test/algorithms/excited_state_solvers/test_excited_states_solvers.py
  test/algorithms/ground_state_solvers/test_adapt_vqe.py
  test/algorithms/ground_state_solvers/test_advanced_ucc_variants.py
  test/algorithms/pes_samplers/potentials/test_potential.py
  test/algorithms/pes_samplers/test_bopes_sampler.py
  test/algorithms/pes_samplers/test_extrapolators.py
  test/drivers/pyscfd/test_driver_methods_pyscf.py
  test/drivers/pyscfd/test_driver_pyscf.py
  test/drivers/pyscfd/test_driver_pyscf_extra.py
  test/drivers/second_quantization/pyscfd/test_driver_methods_pyscf.py
  test/drivers/second_quantization/pyscfd/test_driver_pyscf.py
  test/nature_test_case.py
  test/problems/second_quantization/electronic/builders/test_hopping_ops_builder.py
  test/test_readme_sample.py
  tools/check_copyright.py
  tools/extract_deprecation.py
  tools/generate_spell_dict.py
Labels: type: bug, type: ci, type: enhancement

#280 Fix mapper documentation formatting
  qiskit_nature/mappers/second_quantization/bravyi_kitaev_mapper.py
  qiskit_nature/mappers/second_quantization/direct_mapper.py
  qiskit_nature/mappers/second_quantization/fermionic_mapper.py
  qiskit_nature/mappers/second_quantization/jordan_wigner_mapper.py
  qiskit_nature/mappers/second_quantization/linear_mapper.py
  qiskit_nature/mappers/second_quantization/parity_mapper.py
  qiskit_nature/mappers/second_quantization/qubit_mapper.py
  qiskit_nature/mappers/second_quantization/spin_mapper.py
  qiskit_nature/mappers/second_quantization/vibrational_mapper.py
Labels: type: documentation

#282 [Stable] Add Windows/Mac CI support (#281)
  .github/actions/install-libraries/action.yml
  .github/actions/install-main-dependencies/action.yml
  .github/actions/install-nature/action.yml
  .github/actions/install-psi4/action.yml
  .github/actions/run-tests/action.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  .pylintdict
  .pylintrc
  Makefile
  qiskit_nature/drivers/pyscfd/pyscfdriver.py
  requirements-dev.txt
  test/__init__.py
  test/algorithms/excited_state_solvers/eigensolver_factories/test_numpy_eigensolver_factory.py
  test/algorithms/excited_state_solvers/test_excited_states_solvers.py
  test/algorithms/ground_state_solvers/test_adapt_vqe.py
  test/algorithms/ground_state_solvers/test_advanced_ucc_variants.py
  test/algorithms/pes_samplers/potentials/test_potential.py
  test/algorithms/pes_samplers/test_bopes_sampler.py
  test/algorithms/pes_samplers/test_extrapolators.py
  test/drivers/pyscfd/test_driver_methods_pyscf.py
  test/drivers/pyscfd/test_driver_pyscf.py
  test/drivers/pyscfd/test_driver_pyscf_extra.py
  test/nature_test_case.py
  test/problems/second_quantization/electronic/builders/test_hopping_ops_builder.py
  test/test_readme_sample.py
  tools/check_copyright.py
  tools/extract_deprecation.py
  tools/verify_headers.py
  tox.ini
Labels: type: bug, type: ci, type: enhancement

#284 Add link to repo tutorial on html tutorial prolog
  docs/conf.py
Labels: stable backport potential, type: documentation, type: enhancement

#273 Ground state solvers notebook: remove draw statement without output
  docs/tutorials/03_ground_state_solvers.ipynb
Labels: automerge

#270 W9015: "provider" missing in parameter documentation
  qiskit_nature/runtime/vqe_program.py
Labels: automerge

#286 Fix two qubit reduction for operators that are 2 qubits or less.
  qiskit_nature/converters/second_quantization/qubit_converter.py
  releasenotes/notes/skip-two-qubit-reduction-when-too-small-50ab22e9155db918.yaml
  test/converters/__init__.py
  test/converters/second_quantization/__init__.py
  test/converters/second_quantization/test_qubit_converter.py
Labels: Changelog: Bugfix

#290 Allow `Optimizer`s as input to `VQEProgram`
  qiskit_nature/runtime/vqe_program.py
  releasenotes/notes/vqeprogram-optimizers-cd23307c10fcd15b.yaml
  test/runtime/fake_vqeruntime.py
  test/runtime/test_vqeprogram.py
Labels: Changelog: Bugfix, stable backport potential
