Repository qiskit-community/qiskit-nature, pull requests merged in 2021-11, with the labels that each got.

#397 Speed-up `QubitMapper.mode_based_mapping`
  qiskit_nature/mappers/second_quantization/qubit_mapper.py
Labels: Performance

#408 Fix HartreeFock state under tapering and auto sector locator
  .pylintdict
  qiskit_nature/circuit/library/initial_states/hartree_fock.py
  qiskit_nature/converters/second_quantization/qubit_converter.py
  qiskit_nature/problems/second_quantization/base_problem.py
  qiskit_nature/problems/second_quantization/electronic/electronic_structure_problem.py
  releasenotes/notes/fix_hfstate_auto_symmetry-6038fecf7ef2c822.yaml
  test/circuit/library/initial_states/test_hartree_fock.py
  test/converters/second_quantization/test_qubit_converter.py
  test/problems/second_quantization/electronic/test_electronic_structure_problem.py
Labels: stable backport potential

#420 Support generalized fermionic excitations
  .pylintdict
  qiskit_nature/circuit/library/ansatzes/puccd.py
  qiskit_nature/circuit/library/ansatzes/succd.py
  qiskit_nature/circuit/library/ansatzes/ucc.py
  qiskit_nature/circuit/library/ansatzes/uccsd.py
  qiskit_nature/circuit/library/ansatzes/utils/fermionic_excitation_generator.py
  releasenotes/notes/generalized-fermionic-excitations-1d345d179e097896.yaml
  test/circuit/library/ansatzes/test_puccd.py
  test/circuit/library/ansatzes/test_succd.py
  test/circuit/library/ansatzes/test_uccsd.py
  test/circuit/library/ansatzes/utils/test_fermionic_excitation_generator.py
Labels: Changelog: API Change

#421 Remove Terra 0.19 deprecated messages
  qiskit_nature/circuit/library/initial_states/hartree_fock.py
  qiskit_nature/circuit/library/initial_states/vscf.py
  qiskit_nature/converters/second_quantization/qubit_converter.py
  qiskit_nature/mappers/second_quantization/bksf.py
  qiskit_nature/problems/sampling/protein_folding/qubit_utils/qubit_fixing.py
  qiskit_nature/problems/sampling/protein_folding/qubit_utils/qubit_number_reducer.py
  test/mappers/second_quantization/test_bksf_mapper.py
  test/mappers/second_quantization/test_bravyi_kitaev_mapper.py
  test/mappers/second_quantization/test_jordan_wigner_mapper.py
Labels: type: enhancement

#423 Bump Terra requirements
  requirements.txt
Labels: automerge

#428 Add Gaussian Windows install comment about missing dll
  .pylintdict
  qiskit_nature/drivers/second_quantization/gaussiand/__init__.py
Labels: type: documentation, type: enhancement

#427 Gaussian drivers for python 3.9
  qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cp39-win_amd64.pyd
  qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cpython-39-darwin.so
  qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cpython-39-x86_64-linux-gnu.so
  releasenotes/notes/gaussian-py39-1c519a1bb2f370d3.yaml
Labels: type: enhancement

#435 Fix #434
  qiskit_nature/transformers/second_quantization/electronic/active_space_transformer.py
  releasenotes/notes/fix-active-space-transformer-non-singlet-manual-selection-d022bdbfaccc7e65.yaml
  test/transformers/second_quantization/electronic/test_active_space_transformer.py
Labels: Changelog: Bugfix

#432 Fix EOM with 2Q reduction and tapering
  qiskit_nature/algorithms/excited_states_solvers/qeom.py
  qiskit_nature/problems/second_quantization/electronic/builders/hopping_ops_builder.py
  qiskit_nature/problems/second_quantization/electronic/electronic_structure_problem.py
  releasenotes/notes/qeom_fix-4341f74549f22891.yaml
  test/algorithms/excited_state_solvers/test_excited_states_solvers.py
Labels: Changelog: Bugfix

#438 Update psi4 to stable version on CI
  .github/actions/install-psi4/action.yml
Labels: priority: high, type: ci

#439 Update Mergify to remove deprecation
  .mergify.yml
Labels: type: ci

#425 Update print format of a `VibrationalStructureResult`
  qiskit_nature/results/vibrational_structure_result.py
  releasenotes/notes/print-vibrational-excited-state-energies-0ea51457b3a4a69f.yaml
Labels: Changelog: Bugfix, automerge

#440 Fix mergify automerge condition and disable pylint latest version check on CI
  .github/workflows/main.yml
  .mergify.yml
Labels: priority: high, type: ci

#442 Fix latest pylint errors
  .github/workflows/main.yml
  qiskit_nature/algorithms/pes_samplers/extrapolator.py
  qiskit_nature/drivers/second_quantization/electronic_structure_molecule_driver.py
  qiskit_nature/operators/second_quantization/vibrational_op.py
  qiskit_nature/problems/second_quantization/base_problem.py
  qiskit_nature/problems/second_quantization/electronic/electronic_structure_problem.py
  qiskit_nature/problems/second_quantization/vibrational/vibrational_structure_problem.py
Labels: type: bug, automerge

#443 CI update psi4 windows dev version
  .github/actions/install-psi4/action.yml
Labels: priority: high, type: ci
