Repository qiskit-community/qiskit-nature, pull requests merged in 2021-08, with the labels that each got.

#287 Molecule Driver
  .pylintdict
  docs/tutorials/01_electronic_structure.ipynb
  docs/tutorials/03_ground_state_solvers.ipynb
  docs/tutorials/04_excited_states_solvers.ipynb
  docs/tutorials/05_Sampling_potential_energy_surfaces.ipynb
  docs/tutorials/06_calculating_thermodynamic_observables.ipynb
  docs/tutorials/07_leveraging_qiskit_runtime.ipynb
  qiskit_nature/algorithms/pes_samplers/bopes_sampler.py
  qiskit_nature/drivers/base_driver.py
  qiskit_nature/drivers/bosonic_driver.py
  qiskit_nature/drivers/fermionic_driver.py
  qiskit_nature/drivers/gaussiand/gaussian_forces_driver.py
  qiskit_nature/drivers/gaussiand/gaussiandriver.py
  qiskit_nature/drivers/psi4d/psi4driver.py
  qiskit_nature/drivers/pyquanted/pyquantedriver.py
  qiskit_nature/drivers/pyscfd/pyscfdriver.py
  qiskit_nature/drivers/second_quantization/__init__.py
  qiskit_nature/drivers/second_quantization/base_driver.py
  qiskit_nature/drivers/second_quantization/electronic_structure_driver.py
  qiskit_nature/drivers/second_quantization/electronic_structure_molecule_driver.py
  qiskit_nature/drivers/second_quantization/fcidumpd/fcidumpdriver.py
  qiskit_nature/drivers/second_quantization/gaussiand/gaussian_forces_driver.py
  qiskit_nature/drivers/second_quantization/gaussiand/gaussian_log_driver.py
  qiskit_nature/drivers/second_quantization/gaussiand/gaussian_utils.py
  qiskit_nature/drivers/second_quantization/gaussiand/gaussiandriver.py
  qiskit_nature/drivers/second_quantization/hdf5d/hdf5driver.py
  qiskit_nature/drivers/second_quantization/psi4d/psi4driver.py
  qiskit_nature/drivers/second_quantization/pyquanted/pyquantedriver.py
  qiskit_nature/drivers/second_quantization/pyscfd/pyscfdriver.py
  qiskit_nature/drivers/second_quantization/vibrational_structure_driver.py
  qiskit_nature/drivers/second_quantization/vibrational_structure_molecule_driver.py
  qiskit_nature/problems/second_quantization/electronic/electronic_structure_problem.py
  qiskit_nature/problems/second_quantization/vibrational/vibrational_structure_problem.py
  test/algorithms/excited_state_solvers/test_bosonic_esc_calculation.py
  test/algorithms/pes_samplers/test_bopes_sampler.py
  test/drivers/second_quantization/gaussiand/test_driver_gaussian.py
  test/drivers/second_quantization/gaussiand/test_driver_gaussian_extra.py
  test/drivers/second_quantization/gaussiand/test_driver_gaussian_forces.py
  test/drivers/second_quantization/gaussiand/test_driver_gaussian_from_mat.py
  test/drivers/second_quantization/gaussiand/test_driver_gaussian_log.py
  test/drivers/second_quantization/gaussiand/test_driver_methods_gaussian.py
  test/drivers/second_quantization/psi4d/test_driver_methods_psi4.py
  test/drivers/second_quantization/psi4d/test_driver_psi4.py
  test/drivers/second_quantization/psi4d/test_driver_psi4_extra.py
  test/drivers/second_quantization/pyquanted/test_driver_methods_pyquante.py
  test/drivers/second_quantization/pyquanted/test_driver_pyquante.py
  test/drivers/second_quantization/pyscfd/test_driver_pyscf.py
  test/drivers/second_quantization/test_driver_methods_gsc.py
  test/drivers/second_quantization/test_molecule_driver.py
Labels: type: enhancement

#299 modify h_pq,h_pqrs
  docs/tutorials/01_electronic_structure.ipynb
Labels: type: documentation

#300 Bump reno requirement to latest version and set default_branch
  releasenotes/config.yaml
  requirements-dev.txt
Labels: automerge, stable backport potential

#297 ElectronicStructureMoleculeDriver checks if driver supports method
  qiskit_nature/__init__.py
  qiskit_nature/drivers/second_quantization/electronic_structure_molecule_driver.py
  qiskit_nature/drivers/second_quantization/gaussiand/gaussiandriver.py
  qiskit_nature/drivers/second_quantization/psi4d/psi4driver.py
  qiskit_nature/drivers/second_quantization/pyquanted/pyquantedriver.py
  qiskit_nature/drivers/second_quantization/pyscfd/pyscfdriver.py
  qiskit_nature/drivers/second_quantization/vibrational_structure_molecule_driver.py
  qiskit_nature/exceptions.py
  releasenotes/notes/molecule-driver-762847a396e6bc9e.yaml
  test/drivers/second_quantization/test_molecule_driver.py
Labels: type: bug

#305 Fix CI psi4 install on windows
  .github/actions/install-psi4/action.yml
Labels: priority: critical, automerge, type: ci

#306 [Stable] Fix CI psi4 install on windows (#305)
  .github/actions/install-psi4/action.yml
Labels: type: bug, automerge, type: ci

#232 Implement BKSF for `FermionicOp` input
  .pylintdict
  qiskit_nature/mappers/second_quantization/__init__.py
  qiskit_nature/mappers/second_quantization/bksf.py
  releasenotes/notes/add-bksf-mapper-7826652bfa4403a6.yaml
  test/mappers/second_quantization/test_bksf_mapper.py
Labels: Changelog: New Feature

#315 Remove deprecated QubitConverter
  qiskit_nature/operators/second_quantization/qubit_converter.py
Labels: automerge

#319 Fixes issue #159
  qiskit_nature/algorithms/excited_states_solvers/qeom.py
  qiskit_nature/algorithms/ground_state_solvers/minimum_eigensolver_factories/minimum_eigensolver_factory.py
  qiskit_nature/algorithms/ground_state_solvers/minimum_eigensolver_factories/numpy_minimum_eigensolver_factory.py
  qiskit_nature/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_ucc_factory.py
  qiskit_nature/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_uvcc_factory.py
Labels: type: documentation, automerge

#322 Update docs for UCC and add excitation generators
  .pylintdict
  docs/apidocs/qiskit_nature.circuit.library.ansatzes.utils.rst
  qiskit_nature/circuit/library/__init__.py
  qiskit_nature/circuit/library/ansatzes/__init__.py
  qiskit_nature/circuit/library/ansatzes/ucc.py
  qiskit_nature/circuit/library/ansatzes/utils/__init__.py
  qiskit_nature/circuit/library/ansatzes/uvcc.py
  qiskit_nature/circuit/library/initial_states/__init__.py
Labels: type: documentation

#329 `VQEProgram` should state it supports aux ops
  qiskit_nature/runtime/vqe_program.py
  releasenotes/notes/vqeprogram-aux-operators-9db380d8e20b1f1d.yaml
  test/runtime/test_vqeprogram.py
Labels: Changelog: Bugfix, automerge

#316 Truncate str and repr in FermionicOp
  .pylintdict
  qiskit_nature/operators/second_quantization/fermionic_op.py
Labels: automerge

#334 Updates for Pylint 2.10
  qiskit_nature/algorithms/pes_samplers/bopes_sampler.py
  qiskit_nature/circuit/library/ansatzes/puccd.py
  qiskit_nature/circuit/library/ansatzes/succd.py
  qiskit_nature/circuit/library/ansatzes/utils/fermionic_excitation_generator.py
  qiskit_nature/circuit/library/ansatzes/utils/vibration_excitation_generator.py
  qiskit_nature/drivers/fcidumpd/dumper.py
  qiskit_nature/drivers/fcidumpd/parser.py
  qiskit_nature/drivers/gaussiand/gaussian_log_result.py
  qiskit_nature/drivers/psi4d/psi4driver.py
  qiskit_nature/drivers/pyscfd/integrals.py
  qiskit_nature/drivers/second_quantization/fcidumpd/dumper.py
  qiskit_nature/drivers/second_quantization/fcidumpd/parser.py
  qiskit_nature/drivers/second_quantization/gaussiand/gaussian_log_result.py
  qiskit_nature/drivers/second_quantization/psi4d/psi4driver.py
  qiskit_nature/drivers/second_quantization/pyscfd/pyscfdriver.py
  qiskit_nature/version.py
  test/drivers/gaussiand/test_driver_gaussian_log.py
  test/drivers/second_quantization/gaussiand/test_driver_gaussian_log.py
  test/problems/sampling/protein_folding/resources/file_parser.py
  test/problems/second_quantization/electronic/resources/resource_reader.py
  test/properties/second_quantization/electronic/integrals/test_two_body_electronic_integrals.py
  test/properties/second_quantization/electronic/test_angular_momentum.py
  test/properties/second_quantization/electronic/test_dipole_moment.py
  test/properties/second_quantization/electronic/test_electronic_energy.py
  test/properties/second_quantization/vibrational/bases/test_harmonic_basis.py
  test/properties/second_quantization/vibrational/test_vibrational_energy.py
  tools/extract_deprecation.py
  tools/generate_spell_dict.py
Labels: stable backport potential

#336 Fix docs release notes search
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  Makefile
Labels: priority: high, type: documentation

#344 Fix #343
  qiskit_nature/mappers/second_quantization/bravyi_kitaev_mapper.py
  test/problems/second_quantization/electronic/builders/test_hopping_ops_builder.py
  test/problems/second_quantization/vibrational/builders/test_hopping_ops_builder.py
Labels: priority: critical
