Repository qiskit-community/qiskit-nature, pull requests merged in 2021-02, with the labels that each got.

#33 Fix cvxpy CI install error on python 3.7
  .github/actions/install-master-dependencies/action.yml
Labels: priority: critical, type: bug

#56 Disable parallelism on tutorials job, refactor CI
  .github/actions/install-master-dependencies/action.yml
  .github/workflows/main.yml
Labels: type: bug

#50 Implement the ActiveSpaceTransformer
  .pylintdict
  qiskit_nature/drivers/pyscfd/integrals.py
  qiskit_nature/qmolecule.py
  qiskit_nature/transformations/second_quantization/active_space_transformation.py
  qiskit_nature/transformations/second_quantization/freeze_core_transformation.py
  qiskit_nature/transformations/second_quantization/particle_hole_transformation.py
  qiskit_nature/transformations/second_quantization/second_quantized_transformation.py
  qiskit_nature/transformations/second_quantization/transcorrelated_transformation.py
  qiskit_nature/transformers/__init__.py
  qiskit_nature/transformers/active_space_transformer.py
  qiskit_nature/transformers/base_transformer.py
  qiskit_nature/transformers/freeze_core_transformer.py
  qiskit_nature/transformers/particle_hole_transformer.py
  qiskit_nature/transformers/seniority_zero_transformer.py
  test/transformers/BeH_sto3g.hdf5
  test/transformers/H2_631g.hdf5
  test/transformers/H2_sto3g.hdf5
  test/transformers/H2_sto3g_v2.hdf5
  test/transformers/__init__.py
  test/transformers/test_active_space_transformer.py
Labels: priority: high

#62 Use latest miniconda on psi4 unit test
  .github/actions/install-libraries/action.yml
  .github/actions/install-master-dependencies/action.yml
  .github/actions/install-nature/action.yml
  .github/actions/install-psi4/action.yml
  .github/actions/run-tests/action.yml
  .github/workflows/main.yml
Labels: type: enhancement

#65 Upgrade to pylint 2.7
  constraints.txt
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: type: enhancement
