Repository qiskit-community/qiskit-nature, pull requests merged in 2021-10, with the labels that each got.

#357 Fix mapper
  qiskit_nature/mappers/second_quantization/qubit_mapper.py
  releasenotes/notes/fix-mapper-bug-8eba9d219595b8e1.yaml
  test/mappers/second_quantization/test_bravyi_kitaev_mapper.py
  test/mappers/second_quantization/test_jordan_wigner_mapper.py
  test/mappers/second_quantization/test_parity_mapper.py
  test/problems/second_quantization/electronic/builders/test_hopping_ops_builder.py
  test/problems/second_quantization/vibrational/builders/test_hopping_ops_builder.py
Labels: Changelog: Bugfix, priority: critical, stable backport potential, automerge

#388 Change docs/_templates/layout.html to be equivalento to the one in Qiskit/qiskit repository
  docs/_templates/layout.html
  docs/_templates/theme_variables.jinja
Labels: stable backport potential, type: documentation, automerge

#409 Fix CI Terra visualization install
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: type: bug, type: ci
