Repository qiskit-community/qiskit-nature, pull requests merged in 2021-12, with the labels that each got.

#406 Dict-based `aux_operators`
  .pylintdict
  qiskit_nature/__init__.py
  qiskit_nature/algorithms/excited_states_solvers/excited_states_eigensolver.py
  qiskit_nature/algorithms/excited_states_solvers/excited_states_solver.py
  qiskit_nature/algorithms/excited_states_solvers/qeom.py
  qiskit_nature/algorithms/ground_state_solvers/adapt_vqe.py
  qiskit_nature/algorithms/ground_state_solvers/ground_state_eigensolver.py
  qiskit_nature/algorithms/ground_state_solvers/ground_state_solver.py
  qiskit_nature/converters/second_quantization/qubit_converter.py
  qiskit_nature/converters/second_quantization/utils/__init__.py
  qiskit_nature/converters/second_quantization/utils/list_or_dict.py
  qiskit_nature/problems/second_quantization/base_problem.py
  qiskit_nature/problems/second_quantization/electronic/electronic_structure_problem.py
  qiskit_nature/problems/second_quantization/vibrational/vibrational_structure_problem.py
  qiskit_nature/properties/second_quantization/electronic/angular_momentum.py
  qiskit_nature/properties/second_quantization/electronic/dipole_moment.py
  qiskit_nature/properties/second_quantization/electronic/electronic_structure_driver_result.py
  qiskit_nature/properties/second_quantization/electronic/integrals/integral_property.py
  qiskit_nature/properties/second_quantization/electronic/magnetization.py
  qiskit_nature/properties/second_quantization/electronic/particle_number.py
  qiskit_nature/properties/second_quantization/second_quantized_property.py
  qiskit_nature/properties/second_quantization/vibrational/occupied_modals.py
  qiskit_nature/properties/second_quantization/vibrational/vibrational_energy.py
  qiskit_nature/properties/second_quantization/vibrational/vibrational_structure_driver_result.py
  qiskit_nature/results/eigenstate_result.py
  qiskit_nature/settings.py
  test/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
Labels: Changelog: API Change, type: enhancement

#446 Increase tutorials timeout
  docs/conf.py
Labels: priority: high, automerge, type: ci

#450 Fix pylint errors
  qiskit_nature/problems/sampling/protein_folding/qubit_utils/qubit_number_reducer.py
  qiskit_nature/properties/second_quantization/electronic/dipole_moment.py
  qiskit_nature/properties/second_quantization/electronic/electronic_energy.py
  qiskit_nature/properties/second_quantization/electronic/integrals/integral_property.py
Labels: priority: high, type: bug, automerge

#452 Temporary Remove Python 3.6 from CI
  .github/workflows/main.yml
Labels: priority: high, type: ci

#454 CI - Run python 3.6 unit test using Terra 0.19 from Pypi
  .github/workflows/main.yml
Labels: type: ci

#430 Add Lattice tutorial
  docs/tutorials/10_lattice_models.ipynb
Labels: automerge

#456 Add the Ising model to the Lattice framework
  .pylintdict
  docs/tutorials/10_lattice_models.ipynb
  qiskit_nature/problems/second_quantization/lattice/__init__.py
  qiskit_nature/problems/second_quantization/lattice/lattices/lattice.py
  qiskit_nature/problems/second_quantization/lattice/models/__init__.py
  qiskit_nature/problems/second_quantization/lattice/models/fermi_hubbard_model.py
  qiskit_nature/problems/second_quantization/lattice/models/ising_model.py
  qiskit_nature/problems/second_quantization/lattice/models/lattice_model.py
  releasenotes/notes/add-ising-model-3f6e53c0281bf4a5.yaml
  test/problems/second_quantization/lattice/models/test_fermi_hubbard_model.py
  test/problems/second_quantization/lattice/models/test_ising_model.py
Labels: Changelog: New Feature, automerge

#464 CI - Update PSI4 Windows version
  .github/actions/install-psi4/action.yml
Labels: priority: high, type: ci

#468 Enable some mypy options
  mypy.ini
  qiskit_nature/algorithms/excited_states_solvers/qeom.py
  qiskit_nature/algorithms/pes_samplers/bopes_sampler.py
  qiskit_nature/drivers/bosonic_bases/harmonic_basis.py
  qiskit_nature/drivers/pyscfd/pyscfdriver.py
  qiskit_nature/drivers/second_quantization/electronic_structure_molecule_driver.py
  qiskit_nature/drivers/second_quantization/pyscfd/pyscfdriver.py
  qiskit_nature/drivers/second_quantization/vibrational_structure_molecule_driver.py
  qiskit_nature/operators/second_quantization/fermionic_op.py
  qiskit_nature/problems/second_quantization/electronic/builders/hopping_ops_builder.py
  qiskit_nature/problems/second_quantization/vibrational/builders/hopping_ops_builder.py
  qiskit_nature/properties/second_quantization/electronic/angular_momentum.py
  qiskit_nature/properties/second_quantization/electronic/dipole_moment.py
  qiskit_nature/properties/second_quantization/electronic/magnetization.py
  qiskit_nature/properties/second_quantization/electronic/particle_number.py
  qiskit_nature/properties/second_quantization/vibrational/occupied_modals.py
  qiskit_nature/properties/second_quantization/vibrational/vibrational_energy.py
  qiskit_nature/transformers/second_quantization/electronic/active_space_transformer.py
  qiskit_nature/transformers/second_quantization/electronic/freeze_core_transformer.py
Labels: type: enhancement

#484 Fix mypy error surfaced after latest mypy release
  qiskit_nature/drivers/fcidumpd/fcidumpdriver.py
Labels: priority: high, type: ci

#485 [Stable] Update PSI4 Windows version & fix mypy error surfaced after latest mypy release
  .github/actions/install-psi4/action.yml
  qiskit_nature/drivers/fcidumpd/fcidumpdriver.py
Labels: type: bug, type: ci

#486 Pin sphinxcontrib-spelling due to bug on latest version
  requirements-dev.txt
Labels: priority: high, stable backport potential, type: bug, type: ci
