Repository qiskit-community/qiskit-nature, pull requests merged in 2021-06, with the labels that each got.

#221 Fix #207
  qiskit_nature/transformers/active_space_transformer.py
  releasenotes/notes/fix-active-space-error-formatting-79e4126b65004feb.yaml
  test/transformers/test_active_space_transformer.py
Labels: Changelog: Bugfix

#214 Updated the link leading to a 404 error
  qiskit_nature/drivers/pyscfd/integrals.py
Labels: type: documentation

#215 Updated pyscf github link to the master branch
  qiskit_nature/drivers/pyscfd/__init__.py
Labels: type: documentation

#227 Pin mypy < 0.900
  requirements-dev.txt
Labels: priority: critical, type: bug

#229 Docs - Remove non overidden base methods/attributes from classes
  .pylintdict
  docs/_templates/autosummary/class.rst
  docs/tutorials/05_Sampling_potential_energy_surfaces.ipynb
Labels: type: documentation

#222 Update AdaptVQE to new, stateless VQE
  qiskit_nature/algorithms/ground_state_solvers/adapt_vqe.py
  releasenotes/notes/fix-adapt-vqe-c9df0c06ea352b91.yaml
Labels: priority: critical

#240 Add deprecation method template
  qiskit_nature/algorithms/excited_states_solvers/excited_states_eigensolver.py
  qiskit_nature/circuit/library/ansatzes/uccsd.py
  qiskit_nature/circuit/library/ansatzes/uvccsd.py
  qiskit_nature/deprecation.py
  qiskit_nature/drivers/base_driver.py
  qiskit_nature/drivers/bosonic_bases/bosonic_basis.py
  qiskit_nature/drivers/bosonic_bases/harmonic_basis.py
  qiskit_nature/drivers/fcidumpd/fcidumpdriver.py
  qiskit_nature/drivers/fermionic_driver.py
  qiskit_nature/drivers/gaussiand/gaussian_forces_driver.py
  qiskit_nature/drivers/gaussiand/gaussian_log_driver.py
  qiskit_nature/drivers/gaussiand/gaussian_log_result.py
  qiskit_nature/drivers/gaussiand/gaussiandriver.py
  qiskit_nature/drivers/hdf5d/hdf5driver.py
  qiskit_nature/drivers/psi4d/psi4driver.py
  qiskit_nature/drivers/pyquanted/pyquantedriver.py
  qiskit_nature/drivers/pyscfd/pyscfdriver.py
  qiskit_nature/drivers/qmolecule.py
  qiskit_nature/drivers/second_quantization/gaussiand/gaussian_forces_driver.py
  qiskit_nature/drivers/second_quantization/hdf5d/hdf5driver.py
  qiskit_nature/drivers/watson_hamiltonian.py
  qiskit_nature/operators/second_quantization/qubit_converter.py
  qiskit_nature/operators/second_quantization/star_algebra.py
  qiskit_nature/results/bopes_sampler_result.py
  qiskit_nature/results/electronic_structure_result.py
  qiskit_nature/results/vibrational_structure_result.py
  qiskit_nature/transformers/__init__.py
  qiskit_nature/transformers/second_quantization/active_space_transformer.py
  qiskit_nature/transformers/second_quantization/freeze_core_transformer.py
  test/test_deprecation.py
Labels: type: enhancement

#245 Improvements to deprecate methods
  qiskit_nature/deprecation.py
  test/test_deprecation.py
Labels: type: enhancement

#248 Pin H5Py
  qiskit_nature/algorithms/excited_states_solvers/qeom.py
  qiskit_nature/drivers/bosonic_bases/harmonic_basis.py
  qiskit_nature/drivers/second_quantization/bosonic_bases/harmonic_basis.py
  requirements.txt
Labels: priority: critical

#199 Fix print of ElectronicStructureResult
  qiskit_nature/results/electronic_structure_result.py
  releasenotes/notes/bugfix-totaldipole-0e2271edcdd45cb0.yaml
  test/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
Labels: Changelog: Bugfix

#251 Move away from using pylint header plugin & new deprecate_values decorator
  .github/workflows/main.yml
  .pylintdict
  .pylintrc
  Makefile
  qiskit_nature/deprecation.py
  requirements-dev.txt
  test/test_deprecation.py
  tools/verify_headers.py
  tox.ini
Labels: type: enhancement

#253 Pylint 2.9 Fixes
  qiskit_nature/drivers/fcidumpd/fcidumpdriver.py
  qiskit_nature/drivers/second_quantization/fcidumpd/fcidumpdriver.py
  qiskit_nature/properties/second_quantization/second_quantized_property.py
  qiskit_nature/results/vibrational_structure_result.py
  test/algorithms/excited_state_solvers/test_bosonic_esc_calculation.py
  test/algorithms/excited_state_solvers/test_excited_states_solvers.py
Labels: priority: critical
