Repository qiskit-community/qiskit-nature, pull requests merged in 2021-03, with the labels that each got.

#69 Add Max as code owner
  .github/CODEOWNERS
Labels: type: enhancement

#84 Setup not including top folder files
  setup.py
Labels: type: bug

#81 Remove the mixed-operator: SecondQuantizedOp
  qiskit_nature/mappers/second_quantization/qubit_mapper.py
  qiskit_nature/operators/second_quantization/fermionic_op.py
  qiskit_nature/operators/second_quantization/particle_op.py
  qiskit_nature/operators/second_quantization/qubit_converter.py
  qiskit_nature/operators/second_quantization/second_quantized_op.py
  qiskit_nature/operators/second_quantization/spin_op.py
  qiskit_nature/problems/second_quantization/molecular/molecular_problem.py
  test/operators/second_quantization/test_qubit_converter.py
  test/problems/second_quantization/molecular/test_molecular_problem.py
Labels: priority: high

#85 Hartree-Fock Refactoring
  qiskit_nature/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_uccsd_factory.py
  qiskit_nature/circuit/library/initial_states/hartree_fock.py
  qiskit_nature/transformations/fermionic_transformation.py
  test/algorithms/ground_state_solvers/test_adapt_vqe.py
  test/algorithms/ground_state_solvers/test_swaprz.py
  test/algorithms/pes_samplers/test_bopes_sampler.py
  test/circuit/library/test_hartree_fock.py
  test/components/variational_forms/test_uccsd_advanced.py
  test/components/variational_forms/test_uccsd_hartree_fock.py
  test/components/variational_forms/test_vqe_uccsd_adapt.py
  test/test_readme_sample.py
Labels: priority: critical

#77 ActiveSpaceTransformer generalization
  qiskit_nature/drivers/qmolecule.py
  qiskit_nature/transformers/active_space_transformer.py
  qiskit_nature/transformers/freeze_core_transformer.py
  test/problems/second_quantization/molecular/resources/H2_631g_ferm_op_one_int
  test/problems/second_quantization/molecular/resources/H2_631g_ferm_op_two_ints
  test/problems/second_quantization/molecular/test_molecular_problem.py
  test/transformations/second_quantization/__init__.py
  test/transformers/BeH_sto3g.hdf5
  test/transformers/BeH_sto3g_reduced.hdf5
  test/transformers/H2_631g.hdf5
  test/transformers/H2_sto3g.hdf5
  test/transformers/LiH_sto3g.hdf5
  test/transformers/LiH_sto3g_reduced.hdf5
  test/transformers/test_active_space_transformer.py
  test/transformers/test_freeze_core_transformer.py
Labels: priority: medium, type: enhancement

#100 Remove VariationalForm
  qiskit_nature/components/variational_forms/chc.py
  qiskit_nature/components/variational_forms/uccsd.py
  qiskit_nature/components/variational_forms/uvcc.py
Labels: priority: critical

#66 UCCSD Refactoring
  .pylintdict
  qiskit_nature/__init__.py
  qiskit_nature/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_uccsd_factory.py
  qiskit_nature/circuit/library/__init__.py
  qiskit_nature/circuit/library/ansatzes/__init__.py
  qiskit_nature/circuit/library/ansatzes/evolved_operator_ansatz.py
  qiskit_nature/circuit/library/ansatzes/puccd.py
  qiskit_nature/circuit/library/ansatzes/succd.py
  qiskit_nature/circuit/library/ansatzes/ucc.py
  qiskit_nature/circuit/library/ansatzes/uccsd.py
  qiskit_nature/circuit/library/ansatzes/utils/__init__.py
  qiskit_nature/circuit/library/ansatzes/utils/fermionic_excitation_generator.py
  qiskit_nature/circuit/library/ansatzes/utils/vibration_excitation_generator.py
  qiskit_nature/mp2info.py
  test/circuit/library/ansatzes/__init__.py
  test/circuit/library/ansatzes/test_evolved_op_ansatz.py
  test/circuit/library/ansatzes/test_puccd.py
  test/circuit/library/ansatzes/test_succd.py
  test/circuit/library/ansatzes/test_ucc.py
  test/circuit/library/ansatzes/test_uccsd.py
  test/circuit/library/ansatzes/utils/__init__.py
  test/circuit/library/ansatzes/utils/test_fermionic_excitation_generator.py
  test/circuit/library/ansatzes/utils/test_vibration_excitation_generator.py
  test/circuit/library/initial_states/__init__.py
  test/circuit/library/initial_states/test_hartree_fock.py
  test/circuit/library/initial_states/test_vscf.py
  test/test_mp2info.py
Labels: priority: critical
