Repository qiskit-community/qiskit-nature, pull requests merged in 2021-04, with the labels that each got.

#114 Fix Doc Theme Errors
  .github/workflows/deploy-docs.yml
  docs/_static/gallery.css
  docs/_templates/autosummary/base.rst
  docs/_templates/autosummary/class.rst
  docs/_templates/autosummary/module.rst
  docs/_templates/layout.html
  docs/_templates/page.html
  docs/_templates/theme_variables.jinja
  docs/conf.py
  docs/index.rst
  docs/tutorials/_static/custom.css
  docs/tutorials/_static/style.css
  qiskit_nature/__init__.py
Labels: stable backport potential, type: bug

#115 [Stable] Fix Doc Theme Errors
  .github/workflows/deploy-docs.yml
  docs/_static/gallery.css
  docs/_templates/autosummary/base.rst
  docs/_templates/autosummary/class.rst
  docs/_templates/autosummary/module.rst
  docs/_templates/layout.html
  docs/_templates/page.html
  docs/_templates/theme_variables.jinja
  docs/conf.py
  docs/index.rst
  docs/tutorials/_static/custom.css
  docs/tutorials/_static/style.css
  qiskit_nature/__init__.py
Labels: type: bug

#120 Mergify: configuration update
  .mergify.yml
Labels: stable backport potential, type: enhancement

#126 Disable Conan on CI Aer build. Remove unused retworkx requirement
  .github/actions/install-master-dependencies/action.yml
  .pylintrc
  requirements.txt
Labels: priority: high, stable backport potential, type: bug

#132 Add reno/config.yaml
  releasenotes/config.yaml
Labels: automerge, stable backport potential

#135 Code refactoring
  qiskit_nature/algorithms/excited_states_solvers/qeom.py
  qiskit_nature/algorithms/ground_state_solvers/ground_state_eigensolver.py
  qiskit_nature/drivers/qmolecule.py
  qiskit_nature/mappers/second_quantization/linear_mapper.py
  qiskit_nature/operators/second_quantization/qubit_converter.py
  qiskit_nature/transformers/active_space_transformer.py
Labels: automerge, stable backport potential, type: qa

#131 Fix 128 (Initialization with multi term FermionicOp)
  qiskit_nature/operators/second_quantization/fermionic_op.py
  releasenotes/notes/bugfix-fermionicop-init-4005d72e38ba67f4.yaml
  test/operators/second_quantization/test_fermionic_op.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#140 Make sure CI gets Qiskit dependencies from pypi on stable
  .github/workflows/main.yml
Labels: stable backport potential, type: bug

#141 [Stable] Make sure CI gets Qiskit dependencies from pypi on stable (#140)
  .github/workflows/main.yml
Labels: type: bug

#145 Fix CI slow tests
  .github/actions/run-tests/action.yml
  .github/workflows/main.yml
  test/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
Labels: run_slow

#143 Prepare for renaming default branch to main
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/main.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  qiskit_nature/drivers/gaussiand/__init__.py
  qiskit_nature/version.py
  tox.ini
Labels: stable backport potential

#154 Fix lint msgs caused by latest pylint release
  qiskit_nature/drivers/gaussiand/gaussian_utils.py
  qiskit_nature/drivers/psi4d/psi4driver.py
  qiskit_nature/version.py
  test/drivers/fcidumpd/test_driver_fcidump_dumper.py
  tools/check_copyright.py
Labels: priority: high, stable backport potential, type: bug

#157 Print PendingDeprecation warnings in the CI
  .github/actions/run-tests/action.yml
  .github/workflows/main.yml
Labels: type: ci

#160 Fix test case for gaussian driver
  test/drivers/gaussiand/test_driver_methods_gaussian.py
Labels: Changelog: Bugfix, stable backport potential
