Repository qiskit-community/qiskit-nature, pull requests merged in 2022-12, with the labels that each got.

#985 fix: wrong method name in docstring
  qiskit_nature/second_q/problems/electronic_structure_problem.py
Labels: automerge, stable backport potential

#987 Fix MacOS unit tests
  test/algorithms/excited_state_solvers/test_bosonic_esc_calculation.py
Labels: type: bug, type: ci, stable backport potential

#993 Fix CI Aer install
  .github/actions/install-main-dependencies/action.yml
Labels: automerge, type: ci, stable backport potential

#995 Fix #990
  docs/tutorials/07_leveraging_qiskit_runtime.ipynb
  qiskit_nature/second_q/problems/eigenstate_result.py
  releasenotes/notes/fix-vqe-runtime-client-tutorial-f1e6f91372f89ca5.yaml
Labels: stable backport potential

#998 Pin tox version on doc deploy
  .github/workflows/deploy-docs.yml
Labels: type: bug, type: documentation, automerge

#1000 Update tox configuration file for tox 4.0.2
  .github/workflows/deploy-docs.yml
  tox.ini
Labels: type: ci, stable backport potential

#1004 fix: implement correct commutation relations of `VibrationalOp`
  qiskit_nature/second_q/operators/vibrational_op.py
  releasenotes/notes/fix-vibrational-op-commutation-5cbda6833c0d5232.yaml
  test/second_q/operators/test_vibrational_op.py
Labels: automerge, stable backport potential

#1008 Bind parameters of SparseLabelOp recursively
  qiskit_nature/second_q/operators/sparse_label_op.py
  releasenotes/notes/fix-bind-params-a2851b14e3b8e247.yaml
  test/second_q/operators/test_sparse_label_op.py
Labels: stable backport potential
