Repository qiskit-community/qiskit-nature, pull requests merged in 2022-04, with the labels that each got.

#621 Add `qiskit_nature.settings.optimize_einsum`
  qiskit_nature/properties/second_quantization/electronic/integrals/two_body_electronic_integrals.py
  qiskit_nature/settings.py
  releasenotes/notes/einsum-optimization-27ae7457599e578e.yaml
Labels: automerge

#628 [Stable] Prepare 0.3.2 release
  qiskit_nature/VERSION.txt
Labels: automerge

#630 Remove old gaussian location from manifest and gitignore
  .gitignore
  MANIFEST.in
Labels: automerge

#622 Vectorize `SpinOp.simplify` and `VibrationalOp.simplify`
  qiskit_nature/operators/second_quantization/spin_op.py
  qiskit_nature/operators/second_quantization/vibrational_op.py
Labels: automerge

#638 Improve `TwoBodyElectronicIntegrals.to_second_q_op` performance
  qiskit_nature/properties/second_quantization/electronic/integrals/electronic_integrals.py
  qiskit_nature/properties/second_quantization/electronic/integrals/one_body_electronic_integrals.py
  qiskit_nature/properties/second_quantization/electronic/integrals/two_body_electronic_integrals.py
  releasenotes/notes/performance-two-body-second-q-op-08f906951005ebc1.yaml
Labels: automerge

#639 Set sphinx-build --keep-going by default
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  Makefile
  docs/Makefile
  tox.ini
Labels: type: documentation, type: enhancement

#445 Gradient based AdaptVQE
  .pylintdict
  qiskit_nature/algorithms/ground_state_solvers/adapt_vqe.py
  releasenotes/notes/gradient-based-adapt-vqe-aa4e89f44c5aa69e.yaml
  test/algorithms/ground_state_solvers/test_adapt_vqe.py
Labels: Changelog: API Change, automerge, run_slow, QAMP

#635 Iterate over dict values of aux_op.
  qiskit_nature/runtime/vqe_client.py
  qiskit_nature/runtime/vqe_program.py
  releasenotes/notes/dict_based_aux_ops_in_vqeclient-cef82ff240b51650.yaml
  test/runtime/fake_vqeruntime.py
Labels: automerge

#642 Cache Terra/Aer wheel files in the CI
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/main.yml
Labels: type: enhancement, type: ci

#648 Cache pip env.cache in the CI
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/main.yml
Labels: type: enhancement, type: ci

#590 Migrate MP2Info
  .pylintdict
  qiskit_nature/algorithms/__init__.py
  qiskit_nature/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_ucc_factory.py
  qiskit_nature/algorithms/initial_points/__init__.py
  qiskit_nature/algorithms/initial_points/initial_point.py
  qiskit_nature/algorithms/initial_points/mp2_initial_point.py
  qiskit_nature/circuit/library/ansatzes/ucc.py
  qiskit_nature/circuit/library/ansatzes/uccsd.py
  releasenotes/notes/migrate-mp2-info-b1a3ee7320c46053.yaml
  test/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
  test/algorithms/initial_points/resources/test_mp2_initial_point.json
  test/algorithms/initial_points/test_initial_point.py
  test/algorithms/initial_points/test_mp2_initial_point.py
Labels: Changelog: New Feature, automerge

#649 Fix issue #647
  qiskit_nature/operators/second_quantization/fermionic_op.py
Labels: Performance, automerge

#653 Fix #652
  qiskit_nature/transformers/second_quantization/electronic/freeze_core_transformer.py
  releasenotes/notes/fix-freeze-core-372ac9f9d3ffd4c0.yaml
  test/transformers/second_quantization/electronic/test_freeze_core_transformer.py
Labels: automerge
