Repository qiskit-community/qiskit-nature, pull requests merged in 2022-03, with the labels that each got.

#583 Bump black version and relax constraint
  docs/tutorials/thermodynamics_utils/partition_function.py
  docs/tutorials/thermodynamics_utils/thermodynamics.py
  docs/tutorials/thermodynamics_utils/vibrational_structure_fd.py
  qiskit_nature/algorithms/excited_states_solvers/qeom.py
  qiskit_nature/algorithms/pes_samplers/potentials/morse_potential.py
  qiskit_nature/drivers/second_quantization/fcidumpd/parser.py
  qiskit_nature/drivers/second_quantization/gaussiand/gaussian_log_result.py
  qiskit_nature/operators/second_quantization/spin_op.py
  qiskit_nature/problems/second_quantization/electronic/electronic_structure_problem.py
  qiskit_nature/properties/second_quantization/electronic/integrals/electronic_integrals.py
  requirements-dev.txt
Labels: type: enhancement

#584 Change unit tests to use the new dict. based aux. operators
  qiskit_nature/drivers/second_quantization/gaussiand/gaussian_log_result.py
  test/algorithms/excited_state_solvers/test_excited_states_solvers.py
  test/algorithms/ground_state_solvers/test_adapt_vqe.py
  test/algorithms/ground_state_solvers/test_advanced_ucc_variants.py
  test/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
  test/converters/second_quantization/test_qubit_converter.py
  test/drivers/second_quantization/gaussiand/test_driver_gaussian_log.py
  test/mappers/second_quantization/test_bravyi_kitaev_mapper.py
  test/mappers/second_quantization/test_direct_mapper.py
  test/mappers/second_quantization/test_jordan_wigner_mapper.py
  test/mappers/second_quantization/test_parity_mapper.py
  test/nature_test_case.py
  test/problems/second_quantization/electronic/builders/test_fermionic_op_builder.py
  test/problems/second_quantization/electronic/test_electronic_structure_problem.py
  test/problems/second_quantization/vibrational/test_vibrational_structure_problem.py
  test/properties/second_quantization/electronic/integrals/test_integral_property.py
  test/properties/second_quantization/electronic/test_angular_momentum.py
  test/properties/second_quantization/electronic/test_dipole_moment.py
  test/properties/second_quantization/electronic/test_electronic_energy.py
  test/properties/second_quantization/electronic/test_magnetization.py
  test/properties/second_quantization/electronic/test_particle_number.py
  test/properties/second_quantization/vibrational/test_occupied_modals.py
  test/properties/second_quantization/vibrational/test_vibrational_energy.py
  test/test_end2end_with_vqe.py
Labels: type: enhancement, run_slow

#587 Fix lists in electronic structure tutorial
  docs/tutorials/01_electronic_structure.ipynb
Labels: stable backport potential, type: documentation, automerge

#558 Updated UCC docs
  qiskit_nature/circuit/library/ansatzes/ucc.py
  qiskit_nature/circuit/library/ansatzes/utils/fermionic_excitation_generator.py
Labels: automerge

#594 Pin mypy < 0.940
  requirements-dev.txt
Labels: priority: critical, stable backport potential, type: bug, type: ci

#596 Fix new mypy errors and unpin mypy
  qiskit_nature/algorithms/excited_states_solvers/excited_states_eigensolver.py
  qiskit_nature/algorithms/ground_state_solvers/adapt_vqe.py
  qiskit_nature/algorithms/ground_state_solvers/ground_state_eigensolver.py
  qiskit_nature/drivers/second_quantization/electronic_structure_molecule_driver.py
  requirements-dev.txt
Labels: stable backport potential, type: bug, type: ci

#598 Fix equation in tutorial-06_calculating_thermodynamic_observables.ipynb
  docs/tutorials/06_calculating_thermodynamic_observables.ipynb
Labels: automerge

#599 fix typo
  .pylintdict
  docs/tutorials/05_Sampling_potential_energy_surfaces.ipynb
Labels: stable backport potential, type: documentation, automerge

#603 Fix test_direct_mapper (fix CI breakage)
  test/mappers/second_quantization/test_direct_mapper.py
Labels: automerge

#604 Preparing to publish Japanese docs
  docs/versionutils.py
Labels: stable backport potential, automerge

#611 Pin Jinja2 used by Sphinx
  requirements-dev.txt
Labels: priority: high, stable backport potential, type: bug, type: documentation, automerge

#614 [Stable] Fix latest pylint errors
  qiskit_nature/drivers/pyquanted/integrals.py
  qiskit_nature/drivers/second_quantization/pyquanted/integrals.py
  qiskit_nature/operators/second_quantization/spin_op.py
  qiskit_nature/properties/grouped_property.py
  qiskit_nature/properties/second_quantization/electronic/types.py
  qiskit_nature/properties/second_quantization/second_quantized_property.py
Labels: type: bug

#617 Unpin Jinja2
  requirements-dev.txt
Labels: stable backport potential, type: documentation, automerge

#619 Add apply fixes to copyright checker
  .github/workflows/main.yml
  tools/check_copyright.py
Labels: type: enhancement, type: qa, type: ci
