Repository qiskit-community/qiskit-nature, pull requests merged in 2022-09, with the labels that each got.

#805 Fix initial points with reps
  qiskit_nature/second_q/algorithms/initial_points/hf_initial_point.py
  qiskit_nature/second_q/algorithms/initial_points/mp2_initial_point.py
  qiskit_nature/second_q/algorithms/initial_points/vscf_initial_point.py
  qiskit_nature/second_q/hamiltonians/electronic_energy.py
  qiskit_nature/second_q/properties/bases/electronic_basis.py
  qiskit_nature/second_q/properties/integrals/integral_property.py
  releasenotes/notes/fix-initial-point-with-reps-6157ede7a3b9924a.yaml
  test/second_q/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
  test/second_q/algorithms/initial_points/test_hf_initial_point.py
  test/second_q/algorithms/initial_points/test_mp2_initial_point.py
  test/second_q/algorithms/initial_points/test_vscf_initial_point.py
Labels: automerge

#699 Change mode_based_mapping to instance method
  qiskit_nature/second_q/mappers/bravyi_kitaev_mapper.py
  qiskit_nature/second_q/mappers/direct_mapper.py
  qiskit_nature/second_q/mappers/jordan_wigner_mapper.py
  qiskit_nature/second_q/mappers/parity_mapper.py
  qiskit_nature/second_q/mappers/qubit_mapper.py
  releasenotes/notes/caching-qubit-mapper-ddfc5fae0bda18be.yaml
Labels: automerge, run_slow, Community PR

#821 Keep matplotlib installed in the CI
  .github/workflows/main.yml
Labels: priority: high, automerge, type: ci

#817 Loosen python version requirement from pyscf extra dependency
  setup.py
Labels: automerge

#824 Reinstate removal of matplotlib in CI unit tests
  .github/workflows/main.yml
Labels: type: ci

#520 Implement detecting and transforming index order of two body electronic integrals
  .pylintdict
  docs/apidocs/qiskit_nature.second_q.operators.tensor_ordering.rst
  qiskit_nature/second_q/operators/__init__.py
  qiskit_nature/second_q/operators/tensor_ordering.py
  releasenotes/notes/two-body-symmetry-conversion-db45518ff5fb41bd.yaml
  test/second_q/operators/test_tensor_ordering.py
Labels: automerge

#823 Refactor `FermionicOp` as `SparseLabelOp`
  .pylintdict
  docs/tutorials/10_lattice_models.ipynb
  docs/tutorials/11_quadratic_hamiltonian_and_slater_determinants.ipynb
  docs/tutorials/12_deuteron_binding_energy.ipynb
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom_electronic_ops_builder.py
  qiskit_nature/second_q/circuit/library/ansatzes/ucc.py
  qiskit_nature/second_q/circuit/library/initial_states/hartree_fock.py
  qiskit_nature/second_q/hamiltonians/fermi_hubbard_model.py
  qiskit_nature/second_q/hamiltonians/quadratic_hamiltonian.py
  qiskit_nature/second_q/mappers/bksf.py
  qiskit_nature/second_q/mappers/qubit_converter.py
  qiskit_nature/second_q/mappers/qubit_mapper.py
  qiskit_nature/second_q/operators/fermionic_op.py
  qiskit_nature/second_q/operators/sparse_label_op.py
  qiskit_nature/second_q/properties/integrals/electronic_integrals.py
  qiskit_nature/second_q/properties/integrals/one_body_electronic_integrals.py
  qiskit_nature/second_q/properties/integrals/two_body_electronic_integrals.py
  qiskit_nature/second_q/properties/magnetization.py
  qiskit_nature/second_q/properties/particle_number.py
  releasenotes/notes/fermionic-sparse-label-op-144651db630a8aa1.yaml
  test/second_q/algorithms/excited_state_solvers/test_qeom_electronic_ops.py
  test/second_q/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
  test/second_q/circuit/library/ansatzes/test_puccd.py
  test/second_q/circuit/library/ansatzes/test_succd.py
  test/second_q/circuit/library/ansatzes/test_ucc.py
  test/second_q/circuit/library/ansatzes/test_uccsd.py
  test/second_q/hamiltonians/resources/electronic_energy_op.json
  test/second_q/hamiltonians/test_electronic_energy.py
  test/second_q/hamiltonians/test_fermi_hubbard_model.py
  test/second_q/hamiltonians/test_quadratic_hamiltonian.py
  test/second_q/mappers/resources/bksf_lih.py
  test/second_q/mappers/test_bksf_mapper.py
  test/second_q/mappers/test_bravyi_kitaev_mapper.py
  test/second_q/mappers/test_jordan_wigner_mapper.py
  test/second_q/mappers/test_parity_mapper.py
  test/second_q/mappers/test_qubit_converter.py
  test/second_q/operators/test_fermionic_op.py
  test/second_q/operators/test_sparse_label_op.py
  test/second_q/problems/test_electronic_structure_problem.py
  test/second_q/problems/test_lattice_model_problem.py
  test/second_q/properties/integrals/resources/integral_property_op.json
  test/second_q/properties/integrals/resources/two_body_test_to_second_q_op_alpha_and_beta_expected.json
  test/second_q/properties/integrals/resources/two_body_test_to_second_q_op_only_alpha_expected.json
  test/second_q/properties/integrals/test_integral_property.py
  test/second_q/properties/integrals/test_one_body_electronic_integrals.py
  test/second_q/properties/integrals/test_two_body_electronic_integrals.py
  test/second_q/properties/resources/angular_momentum_op.json
  test/second_q/properties/resources/dipole_moment_ops.json
  test/second_q/properties/resources/electronic_energy_op.json
  test/second_q/properties/test_angular_momentum.py
  test/second_q/properties/test_dipole_moment.py
  test/second_q/properties/test_magnetization.py
  test/second_q/properties/test_particle_number.py
Labels: automerge, run_slow

#825 Use Aer package qiskit_aer
  README.md
  docs/tutorials/03_ground_state_solvers.ipynb
  docs/tutorials/04_excited_states_solvers.ipynb
  docs/tutorials/12_deuteron_binding_energy.ipynb
  requirements-dev.txt
  test/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
  test/algorithms/pes_samplers/test_bopes_sampler.py
  test/second_q/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
Labels: type: enhancement, automerge, run_slow

#826 Pin matplotlib due to bug in retworkx visualization
  .github/actions/install-nature/action.yml
  requirements-dev.txt
  setup.py
Labels: priority: high, bug

#832 Fix unittest module loading errors
  test/circuit/library/initial_states/test_fermionic_gaussian_state.py
  test/circuit/library/initial_states/test_slater_determinant.py
  test/circuit/library/test_bogoliubov_transform.py
  test/nature_random.py
  test/operators/second_quantization/test_quadratic_hamiltonian.py
  test/second_q/circuit/library/initial_states/test_fermionic_gaussian_state.py
  test/second_q/circuit/library/initial_states/test_slater_determinant.py
  test/second_q/circuit/library/test_bogoliubov_transform.py
  test/second_q/hamiltonians/test_quadratic_hamiltonian.py
Labels: type: bug, automerge

#834 Fix #829
  qiskit_nature/runtime/vqe_client.py
  releasenotes/notes/fix-vqe-client-aux-operator-types-ef721cdc127e2fff.yaml
Labels: stable backport potential

#839 Fix doc.deploy script due to matplotlib, retworkx limitation
  .github/workflows/deploy-docs.yml
  requirements-dev.txt
Labels: type: documentation, type: ci

#840 Cache .stestr in CI
  .github/workflows/main.yml
Labels: type: ci

#843 Pin sphinx < 5.2.0 & pyscf < 2.1.1
  docs/conf.py
  requirements-dev.txt
  setup.py
Labels: priority: high, type: bug, type: ci

#844 Unpin sphinx
  requirements-dev.txt
Labels: type: documentation

#845 Fixed mypy latest release errors
  qiskit_nature/algorithms/ground_state_solvers/minimum_eigensolver_factories/numpy_minimum_eigensolver_factory.py
  qiskit_nature/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_ucc_factory.py
  qiskit_nature/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_uvcc_factory.py
  qiskit_nature/problems/second_quantization/base_problem.py
  requirements-dev.txt
  test/test_deprecation.py
Labels: priority: critical, automerge

#846 Enable latest pyscf
  .github/actions/install-psi4/action.yml
  setup.py
Labels: run_slow

#837 Fix convertlib unit test, add error msg
  test/converters/second_quantization/test_qubit_converter.py
Labels: stable backport potential, type: bug

#853 Call base init on VQEClient
  qiskit_nature/runtime/vqe_client.py
Labels: priority: high, automerge
