Repository qiskit-community/qiskit-nature, pull requests merged in 2022-08, with the labels that each got.

#764 Fixed broken links
  CONTRIBUTING.md
Labels: automerge

#697 Fix is_hermitian and add atol
  qiskit_nature/second_q/operators/fermionic_op.py
  qiskit_nature/second_q/operators/second_quantized_op.py
  qiskit_nature/second_q/operators/spin_op.py
  qiskit_nature/second_q/operators/vibrational_op.py
  releasenotes/notes/is-hermitian-33d1000779fba472.yaml
  test/second_q/operators/test_fermionic_op.py
  test/second_q/operators/test_spin_op.py
  test/second_q/operators/test_vibrational_op.py
Labels: automerge

#730 Add method to compute induced norm of SecondQuantizedOp
  qiskit_nature/second_q/operators/second_quantized_op.py
  releasenotes/notes/op-norm-3f4d73df98bc03fc.yaml
  test/second_q/operators/test_fermionic_op.py
Labels: automerge

#726 Adds documentation for the default_filter_criterion
  .pylintdict
  qiskit_nature/second_q/problems/electronic_structure_problem.py
  test/second_q/algorithms/excited_state_solvers/test_excited_states_solvers.py
Labels: automerge

#774 Restore python default behavior for Nature deprecations
  README.md
  qiskit_nature/deprecation.py
  qiskit_nature/settings.py
  test/algorithms/ground_state_solvers/test_adapt_vqe.py
  test/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
  test/algorithms/pes_samplers/test_bopes_sampler.py
  test/nature_test_case.py
  test/second_q/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
Labels: type: qa

#776 Automatically set docs current year
  docs/conf.py
Labels: stable backport potential, type: documentation, automerge

#783 Enable inter-documentation links to be clickable
  docs/conf.py
Labels: stable backport potential, type: documentation

#782 Fix behavior of `FermionicOp.simplify` on zero-operators
  qiskit_nature/operators/second_quantization/fermionic_op.py
  releasenotes/notes/fix-simplify-zero-fermionicop-f2f68e6f19613468.yaml
  test/operators/second_quantization/test_fermionic_op.py
Labels: stable backport potential, automerge

#773 Implement QCSchema.from_legacy_hdf5
  qiskit_nature/second_q/formats/qcschema/qc_schema.py
  qiskit_nature/second_q/formats/qcschema/qc_wavefunction.py
  test/second_q/formats/qcschema/legacy_electronic_structure_driver_result.json
  test/second_q/formats/test_qcschema.py
Labels: automerge

#580 Tutorial: Deuteron binding energy
  .pylintdict
  docs/tutorials/12_deuteron_binding_energy.ipynb
Labels: automerge, Community PR

#766 PropertiesContainer
  docs/conf.py
  qiskit_nature/second_q/problems/__init__.py
  qiskit_nature/second_q/problems/electronic_properties_container.py
  qiskit_nature/second_q/problems/lattice_properties_container.py
  qiskit_nature/second_q/problems/properties_container.py
  qiskit_nature/second_q/problems/vibrational_properties_container.py
  releasenotes/notes/feat-properties-container-a89f4ada04ab5daa.yaml
  test/second_q/problems/test_electronic_properties_container.py
  test/second_q/problems/test_lattice_properties_container.py
  test/second_q/problems/test_properties_container.py
  test/second_q/problems/test_vibrational_properties_container.py
Labels: automerge

#754 Ensure MP2 energy correction matches that from PySCF.
  qiskit_nature/second_q/algorithms/initial_points/__init__.py
  qiskit_nature/second_q/algorithms/initial_points/hf_initial_point.py
  qiskit_nature/second_q/algorithms/initial_points/mp2_initial_point.py
  releasenotes/notes/fix-mp2-energy-correction-8a86c3f073d821d7.yaml
  test/second_q/algorithms/initial_points/resources/test_mp2_initial_point.json
  test/second_q/algorithms/initial_points/test_hf_initial_point.py
  test/second_q/algorithms/initial_points/test_mp2_initial_point.py
Labels: automerge

#591 Heisenberg model
  qiskit_nature/second_q/properties/__init__.py
  qiskit_nature/second_q/properties/heisenberg_model.py
  releasenotes/notes/added-heisenberg-model-218b7ca8386e208a.yaml
  test/problems/second_quantization/lattice/models/test_heisenberg_model.py
Labels: automerge, Community PR

#789 Fix #788
  .pylintdict
  qiskit_nature/circuit/library/ansatzes/utils/fermionic_excitation_generator.py
  qiskit_nature/second_q/circuit/library/ansatzes/utils/fermionic_excitation_generator.py
  releasenotes/notes/fix-generalized-non-spin-preserving-excitations-72745abc12e06c92.yaml
  test/circuit/library/ansatzes/utils/test_fermionic_excitation_generator.py
  test/second_q/circuit/library/ansatzes/utils/test_fermionic_excitation_generator.py
Labels: automerge

#793 [Stable] Fix #788 (#789) backport
  .pylintdict
  qiskit_nature/circuit/library/ansatzes/utils/fermionic_excitation_generator.py
  releasenotes/notes/fix-generalized-non-spin-preserving-excitations-72745abc12e06c92.yaml
  test/circuit/library/ansatzes/utils/test_fermionic_excitation_generator.py
Labels: automerge

#792 Note to avoid confusion with the example
  README.md
Labels: type: documentation

#775 Deprecate protein folding
  qiskit_nature/problems/sampling/protein_folding/__init__.py
  qiskit_nature/problems/sampling/protein_folding/protein_folding_problem.py
  qiskit_nature/problems/sampling/sampling_problem.py
  releasenotes/notes/deprecate-legacy-code-fe9db8a009b6f5d2.yaml
Labels: automerge

#729 Add the `mirror` setting to the `SUCCD` ansatz
  qiskit_nature/second_q/circuit/library/ansatzes/puccd.py
  qiskit_nature/second_q/circuit/library/ansatzes/succd.py
  qiskit_nature/second_q/circuit/library/ansatzes/ucc.py
  releasenotes/notes/feat-succd-mirror-kwarg-5b9f14b11d8992b9.yaml
  test/second_q/algorithms/ground_state_solvers/test_advanced_ucc_variants.py
  test/second_q/circuit/library/ansatzes/test_succd.py
Labels: automerge, Community PR

#798 Load Aer dynamically in unit tests
  test/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
  test/algorithms/pes_samplers/test_bopes_sampler.py
  test/second_q/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
Labels: automerge, run_slow

#807 Enable inter-documentation links to be clickable
  docs/conf.py
Labels: stable backport potential, type: documentation, automerge

#808 Fix existing initial points with reps
  qiskit_nature/algorithms/initial_points/hf_initial_point.py
  qiskit_nature/algorithms/initial_points/mp2_initial_point.py
  qiskit_nature/algorithms/initial_points/vscf_initial_point.py
  releasenotes/notes/fix-existing-initial-point-with-reps-5ca0fd2defe00539.yaml
  test/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
  test/algorithms/initial_points/test_hf_initial_point.py
  test/algorithms/initial_points/test_mp2_initial_point.py
  test/algorithms/initial_points/test_vscf_initial_point.py
Labels: stable backport potential, automerge
