Repository qiskit-community/qiskit-nature, pull requests merged in 2022-05, with the labels that each got.

#656 Update Jordan-Wigner Transformation citation in tutorial notebook
  .pylintdict
  docs/tutorials/01_electronic_structure.ipynb
Labels: automerge

#624 Add LogarithmicMapper
  .pylintdict
  qiskit_nature/mappers/second_quantization/__init__.py
  qiskit_nature/mappers/second_quantization/logarithmic_mapper.py
  releasenotes/notes/logarithmic_mapper-f655fc66d319ba08.yaml
  test/mappers/second_quantization/test_logarithmic_mapper.py
Labels: automerge

#661 Fix CI crash on Ubuntu python 3.8 and 3.9
  .github/workflows/main.yml
  .gitignore
Labels: type: bug, run_slow, type: ci

#662 Add py.typed marker
  MANIFEST.in
  qiskit_nature/py.typed
Labels: type: documentation, type: enhancement

#659 Minor fixes to `ActiveSpaceTransformer`
  .pylintdict
  qiskit_nature/transformers/second_quantization/electronic/active_space_transformer.py
  releasenotes/notes/fix-as-trafo-grouped-property-iteration-bca2096817b1e497.yaml
  test/transformers/second_quantization/electronic/test_active_space_transformer.py
Labels: automerge

#660 Fix #631
  test/drivers/second_quantization/test_molecule_driver.py
Labels: automerge

#663 Fix CI PSI4 crash on Ubuntu
  .github/actions/install-psi4/action.yml
  .github/workflows/main.yml
Labels: priority: critical, run_slow, type: ci

#664 Run CI PSI4 for python 3.10
  .github/actions/install-psi4/action.yml
  .github/workflows/main.yml
Labels: type: enhancement, automerge, run_slow, type: ci

#673 Fix transpiling UCC and UVCC
  .pylintdict
  qiskit_nature/circuit/library/ansatzes/ucc.py
  qiskit_nature/circuit/library/ansatzes/uvcc.py
  releasenotes/notes/fix-transpile-uccsd-db7f2557e6155017.yaml
  test/circuit/library/ansatzes/test_chc.py
  test/circuit/library/ansatzes/test_ucc.py
  test/circuit/library/ansatzes/test_uvcc.py
Labels: type: bug, automerge
