Repository qiskit-community/qiskit-nature, pull requests merged in 2022-02, with the labels that each got.

#527 Temporarily skip broken tests
  test/algorithms/excited_state_solvers/test_excited_states_solvers.py
  test/algorithms/ground_state_solvers/test_advanced_ucc_variants.py
Labels: priority: critical

#507 Fix register_length inference
  qiskit_nature/operators/second_quantization/fermionic_op.py
  releasenotes/notes/fix-inference-of-register-length-cf23f13a477e9e57.yaml
  test/operators/second_quantization/test_fermionic_op.py
Labels: Changelog: Bugfix, stable backport potential

#526 Revert #176
  docs/conf.py
Labels: automerge

#512 Use dot rather than obsolete * for composing ops
  qiskit_nature/mappers/second_quantization/bksf.py
  releasenotes/notes/bksf-fix-op-compose-bc8161a50bf9acaa.yaml
  test/mappers/second_quantization/resources/bksf_lih.py
  test/mappers/second_quantization/test_bksf_mapper.py
Labels: stable backport potential, automerge

#525 PyQuante Driver Update
  qiskit_nature/constants.py
  qiskit_nature/drivers/qmolecule.py
  qiskit_nature/drivers/second_quantization/gaussiand/gaussiandriver.py
  qiskit_nature/drivers/second_quantization/pyquanted/integrals.py
  qiskit_nature/drivers/second_quantization/pyquanted/pyquantedriver.py
  qiskit_nature/drivers/second_quantization/pyscfd/pyscfdriver.py
  qiskit_nature/transformers/second_quantization/electronic/freeze_core_transformer.py
Labels: automerge

#536 fix: propagate truncation_order from VibrationalStructureProblem
  docs/tutorials/02_vibrational_structure.ipynb
  qiskit_nature/problems/second_quantization/vibrational/vibrational_structure_problem.py
  releasenotes/notes/vibrational-truncation-order-92ebbd78cc2c29fa.yaml
  test/problems/second_quantization/vibrational/test_vibrational_structure_problem.py
Labels: Changelog: Bugfix, priority: high, stable backport potential, automerge

#451 Handle corner cases in BKSF mapper
  qiskit_nature/circuit/library/initial_states/hartree_fock.py
  qiskit_nature/mappers/second_quantization/bksf.py
  releasenotes/notes/bksf-fix-corner-cases-7f66d695fc316e9a.yaml
  test/mappers/second_quantization/test_bksf_mapper.py
Labels: stable backport potential, automerge

#535 Adopt lazy imports from Terra
  qiskit_nature/drivers/second_quantization/electronic_structure_molecule_driver.py
  qiskit_nature/drivers/second_quantization/gaussiand/gaussian_forces_driver.py
  qiskit_nature/drivers/second_quantization/gaussiand/gaussian_log_driver.py
  qiskit_nature/drivers/second_quantization/gaussiand/gaussian_utils.py
  qiskit_nature/drivers/second_quantization/gaussiand/gaussiandriver.py
  qiskit_nature/drivers/second_quantization/psi4d/psi4driver.py
  qiskit_nature/drivers/second_quantization/pyquanted/pyquantedriver.py
  qiskit_nature/drivers/second_quantization/pyscfd/pyscfdriver.py
  qiskit_nature/drivers/second_quantization/vibrational_structure_molecule_driver.py
  qiskit_nature/optionals.py
  qiskit_nature/problems/second_quantization/lattice/lattices/lattice.py
  test/__init__.py
  test/algorithms/excited_state_solvers/eigensolver_factories/test_numpy_eigensolver_factory.py
  test/algorithms/excited_state_solvers/test_bosonic_esc_calculation.py
  test/algorithms/excited_state_solvers/test_excited_states_solvers.py
  test/algorithms/ground_state_solvers/test_adapt_vqe.py
  test/algorithms/ground_state_solvers/test_advanced_ucc_variants.py
  test/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
  test/algorithms/ground_state_solvers/test_swaprz.py
  test/algorithms/pes_samplers/test_bopes_sampler.py
  test/drivers/second_quantization/fcidumpd/test_driver_fcidump_dumper.py
  test/drivers/second_quantization/gaussiand/test_driver_gaussian.py
  test/drivers/second_quantization/gaussiand/test_driver_gaussian_extra.py
  test/drivers/second_quantization/gaussiand/test_driver_gaussian_forces.py
  test/drivers/second_quantization/gaussiand/test_driver_gaussian_from_mat.py
  test/drivers/second_quantization/gaussiand/test_driver_gaussian_log.py
  test/drivers/second_quantization/gaussiand/test_driver_methods_gaussian.py
  test/drivers/second_quantization/psi4d/test_driver_methods_psi4.py
  test/drivers/second_quantization/psi4d/test_driver_psi4.py
  test/drivers/second_quantization/psi4d/test_driver_psi4_extra.py
  test/drivers/second_quantization/pyquanted/test_driver_methods_pyquante.py
  test/drivers/second_quantization/pyquanted/test_driver_pyquante.py
  test/drivers/second_quantization/pyscfd/test_driver_methods_pyscf.py
  test/drivers/second_quantization/pyscfd/test_driver_pyscf.py
  test/drivers/second_quantization/test_molecule_driver.py
  test/nature_test_case.py
  test/problems/second_quantization/electronic/builders/test_hopping_ops_builder.py
  test/problems/second_quantization/electronic/test_electronic_structure_problem.py
  test/test_readme_sample.py
Labels: type: enhancement, run_slow

#543 Use code from README.md in test_readme_sample
  README.md
  test/test_readme_sample.py
Labels: type: enhancement, type: ci

#532 [Stable] Add support for Python 3.10
  .github/workflows/main.yml
  pyproject.toml
  qiskit_nature/drivers/gaussiand/gauopen/qcmatrixio.cp310-win_amd64.pyd
  qiskit_nature/drivers/gaussiand/gauopen/qcmatrixio.cp39-win_amd64.pyd
  qiskit_nature/drivers/gaussiand/gauopen/qcmatrixio.cpython-310-darwin.so
  qiskit_nature/drivers/gaussiand/gauopen/qcmatrixio.cpython-310-x86_64-linux-gnu.so
  qiskit_nature/drivers/gaussiand/gauopen/qcmatrixio.cpython-39-darwin.so
  qiskit_nature/drivers/gaussiand/gauopen/qcmatrixio.cpython-39-x86_64-linux-gnu.so
  qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cp310-win_amd64.pyd
  qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cpython-310-darwin.so
  qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cpython-310-x86_64-linux-gnu.so
  releasenotes/notes/add-python310-support-6ef188b2e1572cc8.yaml
  setup.py
  tox.ini
Labels: automerge

#524 Alter forces test based on driver revision
  docs/tutorials/02_vibrational_structure.ipynb
  docs/tutorials/03_ground_state_solvers.ipynb
  docs/tutorials/08_property_framework.ipynb
  docs/tutorials/aux_files/CO2_freq_B3LYP_631g.log
  docs/tutorials/aux_files/CO2_freq_B3LYP_ccpVDZ.log
  test/drivers/second_quantization/gaussiand/test_driver_gaussian_forces.py
  test/drivers/second_quantization/gaussiand/test_driver_gaussian_log.py
  test/drivers/second_quantization/gaussiand/test_driver_gaussian_log_A03.txt
  test/drivers/second_quantization/gaussiand/test_driver_gaussian_log_C01.txt
  test/mappers/second_quantization/resources/reference_direct_mapper.py
  test/mappers/second_quantization/test_direct_mapper.py
  test/problems/second_quantization/vibrational/resources/CO2_freq_B3LYP_ccpVDZ.log
  test/problems/second_quantization/vibrational/resources/expected_labels.py
  test/problems/second_quantization/vibrational/resources/expected_ops.py
  test/problems/second_quantization/vibrational/test_vibrational_structure_problem.py
Labels: priority: high, stable backport potential

#548 [Stable] Prepare 0.3.1 release
  qiskit_nature/VERSION.txt
Labels: automerge

#554 Update `load_from_hdf5`
  qiskit_nature/hdf5.py
  test/resources/test_hdf5_error_import_failure.hdf5
  test/resources/test_hdf5_error_missing_class.hdf5
  test/resources/test_hdf5_error_multiple_groups.hdf5
  test/resources/test_hdf5_error_non_native.hdf5
  test/resources/test_hdf5_error_non_protocol.hdf5
  test/test_hdf5.py
Labels: priority: high

#472 Support ``networkx.Graph``s as input to ``Lattice``
  .pylintdict
  qiskit_nature/problems/second_quantization/lattice/lattices/lattice.py
  releasenotes/notes/lattice-from-networkx-20c7c8119af77f36.yaml
  test/problems/second_quantization/lattice/lattices/test_lattice.py
Labels: Changelog: New Feature, automerge

#552 Gaussian driver updates
  qiskit_nature/drivers/second_quantization/gaussiand/gaussian_forces_driver.py
  qiskit_nature/drivers/second_quantization/gaussiand/gaussian_log_driver.py
  qiskit_nature/drivers/second_quantization/gaussiand/gaussian_log_result.py
  qiskit_nature/drivers/second_quantization/gaussiand/gaussiandriver.py
  test/drivers/second_quantization/gaussiand/test_driver_gaussian_from_mat.py
  test/drivers/second_quantization/gaussiand/test_driver_gaussian_log.py
  test/drivers/second_quantization/gaussiand/test_driver_gaussian_log_vibrational_energy.hdf5
  test/drivers/second_quantization/test_driver_methods_gsc.py
  test/problems/sampling/protein_folding/resources/file_parser.py
Labels: automerge

#530 perf: remove unneeded reduction in IntegralProperty
  qiskit_nature/properties/second_quantization/electronic/integrals/integral_property.py
  test/problems/second_quantization/electronic/builders/test_fermionic_op_builder.py
  test/problems/second_quantization/electronic/resources/H2_631g_ferm_op_active_space
  test/problems/second_quantization/electronic/resources/H2_631g_ferm_op_one_int
  test/problems/second_quantization/electronic/resources/H2_631g_ferm_op_two_ints
  test/properties/second_quantization/electronic/integrals/resources/integral_property_op.json
  test/properties/second_quantization/electronic/integrals/test_integral_property.py
  test/properties/second_quantization/electronic/resources/dipole_moment_ops.json
  test/properties/second_quantization/electronic/resources/electronic_energy_op.json
Labels: automerge

#533 reduce memory usage of `ElectronicIntegrals`
  docs/tutorials/08_property_framework.ipynb
  qiskit_nature/properties/second_quantization/electronic/bases/electronic_basis_transform.py
  qiskit_nature/properties/second_quantization/electronic/electronic_energy.py
  qiskit_nature/properties/second_quantization/electronic/integrals/electronic_integrals.py
  qiskit_nature/properties/second_quantization/electronic/integrals/one_body_electronic_integrals.py
  qiskit_nature/properties/second_quantization/electronic/integrals/two_body_electronic_integrals.py
  test/properties/property_test.py
  test/properties/second_quantization/electronic/integrals/test_integral_property.py
  test/properties/second_quantization/electronic/integrals/test_one_body_electronic_integrals.py
  test/properties/second_quantization/electronic/integrals/test_two_body_electronic_integrals.py
  test/properties/second_quantization/electronic/resources/electronic_structure_driver_result.hdf5
Labels: automerge

#560 Apply simplify to creation_op and annihilation_op in qubit mapping
  qiskit_nature/mappers/second_quantization/qubit_mapper.py
Labels: automerge

#566 Revert "Temporarily skip broken tests (#527)"
  test/algorithms/excited_state_solvers/test_excited_states_solvers.py
  test/algorithms/ground_state_solvers/test_advanced_ucc_variants.py
Labels: automerge, run_slow

#568 Fix #567, `_build` directory not being excluded by Black
  Makefile
  tox.ini
Labels: stable backport potential

#565 Create logging utility functions
  .pylintdict
  docs/apidocs/qiskit_nature.logging.rst
  docs/apidocs/qiskit_nature.settings.rst
  qiskit_nature/__init__.py
  qiskit_nature/logging.py
  qiskit_nature/settings.py
  releasenotes/notes/add-logging-171aceb37c21a3d5.yaml
  test/test_logging.py
Labels: type: enhancement

#572 Preparing to publish Bengali docs
  docs/versionutils.py
  tools/deploy_documentation.sh
Labels: stable backport potential, type: documentation, automerge

#573 fix: catch DriverMetadata-related warnings during transform
  qiskit_nature/transformers/second_quantization/electronic/active_space_transformer.py
Labels: automerge
