Repository qiskit-community/qiskit-nature, pull requests merged in 2022-06, with the labels that each got.

#678 Remove long-deprecated Objects
  qiskit_nature/operators/second_quantization/second_quantized_op.py
  qiskit_nature/operators/second_quantization/star_algebra.py
  qiskit_nature/problems/second_quantization/electronic/builders/fermionic_op_builder.py
  test/problems/second_quantization/electronic/builders/test_fermionic_op_builder.py
Labels: automerge

#682 Run CI unit tests step without matplotlib,pyscf,psi4,pyquante2
  .github/workflows/main.yml
Labels: run_slow, type: ci

#687 Run tutorials without miniconda
  .github/actions/install-main-dependencies/action.yml
  .github/actions/install-nature/action.yml
  .github/workflows/main.yml
Labels: type: ci

#646 Replace #570. VQE factories.
  .gitignore
  docs/tutorials/03_ground_state_solvers.ipynb
  docs/tutorials/04_excited_states_solvers.ipynb
  qiskit_nature/algorithms/ground_state_solvers/ground_state_eigensolver.py
  qiskit_nature/algorithms/ground_state_solvers/minimum_eigensolver_factories/minimum_eigensolver_factory.py
  qiskit_nature/algorithms/ground_state_solvers/minimum_eigensolver_factories/numpy_minimum_eigensolver_factory.py
  qiskit_nature/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_ucc_factory.py
  qiskit_nature/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_uvcc_factory.py
  qiskit_nature/deprecation.py
  releasenotes/notes/vqe-factory-improvements-02f411513f11907c.yaml
  test/algorithms/excited_state_solvers/test_bosonic_esc_calculation.py
  test/algorithms/excited_state_solvers/test_excited_states_solvers.py
  test/algorithms/ground_state_solvers/minimum_eigensolver_factories/test_vqe_ucc_factory.py
  test/algorithms/ground_state_solvers/minimum_eigensolver_factories/test_vqe_uvcc_factory.py
  test/algorithms/ground_state_solvers/test_adapt_vqe.py
  test/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
  test/algorithms/pes_samplers/test_bopes_sampler.py
  test/test_deprecation.py
Labels: automerge

#655 ProteinFoldingResult, XYZ files and plotting of folded Proteins for ProteinFoldingProblem.
  docs/apidocs/qiskit_nature.results.utils.rst
  docs/tutorials/09_Protein_Folding.ipynb
  qiskit_nature/problems/sampling/protein_folding/protein_folding_problem.py
  qiskit_nature/problems/sampling/sampling_problem.py
  qiskit_nature/problems/second_quantization/lattice/lattices/lattice.py
  qiskit_nature/results/__init__.py
  qiskit_nature/results/protein_folding_result.py
  qiskit_nature/results/utils/__init__.py
  qiskit_nature/results/utils/protein_plotter.py
  qiskit_nature/results/utils/protein_shape_decoder.py
  qiskit_nature/results/utils/protein_shape_file_gen.py
  releasenotes/notes/protein-folding-result-b344ac3c7f48e3ca.yaml
  requirements-dev.txt
  setup.py
  test/results/test_protein_folding_result.py
  test/results/utils/__init__.py
  test/results/utils/resources/also_side_chains_test.xyz
  test/results/utils/resources/only_main_chain_test.xyz
  test/results/utils/test_protein_decoder.py
  test/results/utils/test_protein_shape_file_gen.py
Labels: automerge

#691 Prepare 0.4.0 Release
  releasenotes/notes/0.4/BOPERSampler-supports-MinimumEigensolverFactories-d920a7870d7e265d.yaml
  releasenotes/notes/0.4/add-hf-initial-point-ac29baf3091fa5b1.yaml
  releasenotes/notes/0.4/add-logging-171aceb37c21a3d5.yaml
  releasenotes/notes/0.4/add-python310-support-6ef188b2e1572cc8.yaml
  releasenotes/notes/0.4/added_support-of-bohr-unit-4b27ef4b89f7ee32.yaml
  releasenotes/notes/0.4/bksf-fix-corner-cases-7f66d695fc316e9a.yaml
  releasenotes/notes/0.4/bksf-fix-op-compose-bc8161a50bf9acaa.yaml
  releasenotes/notes/0.4/bogoliubov-transform-885eb6442172c76e.yaml
  releasenotes/notes/0.4/dict_based_aux_ops_in_vqeclient-cef82ff240b51650.yaml
  releasenotes/notes/0.4/drop-python3.6-support-ea12d78ea8616c74.yaml
  releasenotes/notes/0.4/einsum-optimization-27ae7457599e578e.yaml
  releasenotes/notes/0.4/fermionicop-iter-a60ae0ed7e3cff1e.yaml
  releasenotes/notes/0.4/fermionicop-sparse-format-3aa7c9d52b9396e4.yaml
  releasenotes/notes/0.4/fix-as-trafo-grouped-property-iteration-bca2096817b1e497.yaml
  releasenotes/notes/0.4/fix-freeze-core-372ac9f9d3ffd4c0.yaml
  releasenotes/notes/0.4/fix-inference-of-register-length-cf23f13a477e9e57.yaml
  releasenotes/notes/0.4/fix-molecule-coordinate-units-61f109372dcf7842.yaml
  releasenotes/notes/0.4/fix-non-singlet-occupation-computation-f2ff44b144b53732.yaml
  releasenotes/notes/0.4/fix-transpile-uccsd-db7f2557e6155017.yaml
  releasenotes/notes/0.4/fix_groundenergy-f973527ae6296c59.yaml
  releasenotes/notes/0.4/fix_uccsd_op_build-6b0bc1de57f3e423.yaml
  releasenotes/notes/0.4/gradient-based-adapt-vqe-aa4e89f44c5aa69e.yaml
  releasenotes/notes/0.4/hdf5-driver-bafbbd8e70ee15a6.yaml
  releasenotes/notes/0.4/hdf5-integration-b08c31426d1fdf9e.yaml
  releasenotes/notes/0.4/initialize-ferop-with-tuple-as-label-0dc3f1dbd754ca29.yaml
  releasenotes/notes/0.4/lattice-edge-typecheck-3f5b4896fe26c8dc.yaml
  releasenotes/notes/0.4/lattice-from-networkx-20c7c8119af77f36.yaml
  releasenotes/notes/0.4/lattice_model_problem-3925bfbd2267cd4c.yaml
  releasenotes/notes/0.4/logarithmic_mapper-f655fc66d319ba08.yaml
  releasenotes/notes/0.4/migrate-mp2-info-b1a3ee7320c46053.yaml
  releasenotes/notes/0.4/performance-two-body-second-q-op-08f906951005ebc1.yaml
  releasenotes/notes/0.4/protein-folding-result-b344ac3c7f48e3ca.yaml
  releasenotes/notes/0.4/quad-ham-7c98cc11f700bdc5.yaml
  releasenotes/notes/0.4/simplify-01d1b75c00a7eac9.yaml
  releasenotes/notes/0.4/slater-53415163fff84313.yaml
  releasenotes/notes/0.4/support_excitedstatessolver_bopes-2bbb5a282b1ff582.yaml
  releasenotes/notes/0.4/uvcc_op_creation-bac88e1f58c781ae.yaml
  releasenotes/notes/0.4/vibrational-truncation-order-92ebbd78cc2c29fa.yaml
  releasenotes/notes/0.4/vqe-factory-improvements-02f411513f11907c.yaml
  releasenotes/notes/0.4/vqeclient-extends-variationalalg-eb5b3f951405fd16.yaml
Labels: automerge

#695 bump min terra version to 0.21
  requirements.txt
Labels: automerge

#700 Add missing instructions for docs. build
  CONTRIBUTING.md
Labels: type: documentation

#712 Fixes integer-based isinstance checks to also handle numpy integers.
  qiskit_nature/properties/second_quantization/electronic/angular_momentum.py
  qiskit_nature/properties/second_quantization/electronic/magnetization.py
  qiskit_nature/properties/second_quantization/electronic/particle_number.py
  qiskit_nature/transformers/second_quantization/electronic/active_space_transformer.py
  releasenotes/notes/fix-isinstance-integer-checks-50f7614393e68e87.yaml
  test/transformers/second_quantization/electronic/test_active_space_transformer.py
Labels: stable backport potential

#719 fix: do not hard-code minor Terra version
  requirements.txt
Labels: priority: critical, type: ci

#721 Remove pbark as a code owner
  .github/CODEOWNERS
Labels: stable backport potential

#723 switched to sphinx-design
  docs/conf.py
  docs/getting_started.rst
  requirements-dev.txt
Labels: stable backport potential, type: documentation, automerge
