Repository qiskit-community/qiskit-nature, pull requests merged in 2022-10, with the labels that each got.

#868 Change from retworkx to rustworkx, pylint whitelist rustworkx
  .pylintdict
  .pylintrc
  docs/conf.py
  qiskit_nature/problems/second_quantization/lattice/lattices/hyper_cubic_lattice.py
  qiskit_nature/problems/second_quantization/lattice/lattices/lattice.py
  qiskit_nature/problems/second_quantization/lattice/lattices/triangular_lattice.py
  qiskit_nature/problems/second_quantization/lattice/models/lattice_model.py
  qiskit_nature/second_q/hamiltonians/lattices/hyper_cubic_lattice.py
  qiskit_nature/second_q/hamiltonians/lattices/lattice.py
  qiskit_nature/second_q/hamiltonians/lattices/triangular_lattice.py
  releasenotes/notes/retworkx-rustworkx-7836a84db7669814.yaml
  requirements.txt
  test/problems/second_quantization/lattice/lattices/test_hyper_cubic_lattice.py
  test/problems/second_quantization/lattice/lattices/test_lattice.py
  test/problems/second_quantization/lattice/lattices/test_line_lattice.py
  test/problems/second_quantization/lattice/lattices/test_square_lattice.py
  test/problems/second_quantization/lattice/lattices/test_triangular_lattice.py
  test/problems/second_quantization/lattice/models/test_fermi_hubbard_model.py
  test/problems/second_quantization/lattice/models/test_ising_model.py
  test/second_q/hamiltonians/lattices/test_hyper_cubic_lattice.py
  test/second_q/hamiltonians/lattices/test_lattice.py
  test/second_q/hamiltonians/lattices/test_line_lattice.py
  test/second_q/hamiltonians/lattices/test_square_lattice.py
  test/second_q/hamiltonians/lattices/test_triangular_lattice.py
  test/second_q/hamiltonians/test_fermi_hubbard_model.py
  test/second_q/hamiltonians/test_heisenberg_model.py
  test/second_q/hamiltonians/test_ising_model.py
Labels: priority: critical, type: bug

#871 Fix setuptools incompatibility version with setuptools_rust
  .github/actions/install-main-dependencies/action.yml
Labels: automerge, type: ci

#872 Update Github Actions versions
  .github/workflows/deploy-code.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: type: enhancement, type: ci

#874 refactor: handle subclass keyword arguments of SparseLabelOp
  docs/tutorials/01_electronic_structure.ipynb
  docs/tutorials/10_lattice_models.ipynb
  docs/tutorials/11_quadratic_hamiltonian_and_slater_determinants.ipynb
  docs/tutorials/12_deuteron_binding_energy.ipynb
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom_electronic_ops_builder.py
  qiskit_nature/second_q/circuit/library/ansatzes/ucc.py
  qiskit_nature/second_q/circuit/library/initial_states/hartree_fock.py
  qiskit_nature/second_q/hamiltonians/fermi_hubbard_model.py
  qiskit_nature/second_q/hamiltonians/quadratic_hamiltonian.py
  qiskit_nature/second_q/operators/fermionic_op.py
  qiskit_nature/second_q/operators/sparse_label_op.py
  qiskit_nature/second_q/properties/magnetization.py
  qiskit_nature/second_q/properties/particle_number.py
  test/second_q/circuit/library/ansatzes/test_puccd.py
  test/second_q/circuit/library/ansatzes/test_succd.py
  test/second_q/circuit/library/ansatzes/test_ucc.py
  test/second_q/circuit/library/ansatzes/test_uccsd.py
  test/second_q/hamiltonians/test_fermi_hubbard_model.py
  test/second_q/hamiltonians/test_quadratic_hamiltonian.py
  test/second_q/mappers/resources/bksf_lih.py
  test/second_q/mappers/test_bksf_mapper.py
  test/second_q/mappers/test_bravyi_kitaev_mapper.py
  test/second_q/mappers/test_jordan_wigner_mapper.py
  test/second_q/mappers/test_parity_mapper.py
  test/second_q/mappers/test_qubit_converter.py
  test/second_q/operators/test_fermionic_op.py
  test/second_q/operators/test_sparse_label_op.py
  test/second_q/properties/test_angular_momentum.py
Labels: priority: high, run_slow

#870 Sparse `PolynomialTensor`
  .github/actions/install-nature/action.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  .pylintdict
  qiskit_nature/optionals.py
  qiskit_nature/second_q/operators/electronic_integrals.py
  qiskit_nature/second_q/operators/fermionic_op.py
  qiskit_nature/second_q/operators/polynomial_tensor.py
  qiskit_nature/second_q/operators/tensor_ordering.py
  setup.py
  test/second_q/drivers/gaussiand/test_driver_gaussian_from_mat.py
  test/second_q/formats/fcidump/test_methods_fcidump.py
  test/second_q/operators/test_electronic_integrals.py
  test/second_q/operators/test_fermionic_op.py
  test/second_q/operators/test_polynomial_tensor.py
  test/second_q/operators/test_spin_op.py
  test/second_q/operators/test_tensor_ordering.py
  test/second_q/properties/test_angular_momentum.py
Labels: automerge, run_slow

#876 Update CI actions/setup-python version
  .github/workflows/deploy-code.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: type: enhancement, automerge, type: ci

#878 Detailed sparse library check
  qiskit_nature/second_q/operators/fermionic_op.py
  qiskit_nature/second_q/operators/polynomial_tensor.py
  test/second_q/drivers/gaussiand/test_driver_gaussian_from_mat.py
  test/second_q/formats/fcidump/test_methods_fcidump.py
  test/second_q/operators/test_electronic_integrals.py
  test/second_q/operators/test_fermionic_op.py
  test/second_q/operators/test_tensor_ordering.py
  test/second_q/properties/test_angular_momentum.py
Labels: type: enhancement

#882 Fix Sphinx doc. build for python 3.9
  .github/workflows/main.yml
  qiskit_nature/second_q/hamiltonians/electronic_energy.py
  qiskit_nature/second_q/hamiltonians/hamiltonian.py
  qiskit_nature/second_q/hamiltonians/vibrational_energy.py
  qiskit_nature/second_q/properties/angular_momentum.py
  qiskit_nature/second_q/properties/dipole_moment.py
  qiskit_nature/second_q/properties/electronic_density.py
  qiskit_nature/second_q/properties/magnetization.py
  qiskit_nature/second_q/properties/occupied_modals.py
  qiskit_nature/second_q/properties/particle_number.py
Labels: type: bug, type: documentation, automerge

#884 fix num_spin_orbitals for FermionicOp with zero spin orbitals
  qiskit_nature/second_q/operators/fermionic_op.py
  test/second_q/operators/test_fermionic_op.py
Labels: automerge

#895 Fix type hint EigenstateResult path
  qiskit_nature/second_q/hamiltonians/electronic_energy.py
  qiskit_nature/second_q/hamiltonians/hamiltonian.py
  qiskit_nature/second_q/hamiltonians/vibrational_energy.py
  qiskit_nature/second_q/properties/angular_momentum.py
  qiskit_nature/second_q/properties/dipole_moment.py
  qiskit_nature/second_q/properties/electronic_density.py
  qiskit_nature/second_q/properties/magnetization.py
  qiskit_nature/second_q/properties/occupied_modals.py
  qiskit_nature/second_q/properties/particle_number.py
Labels: type: bug, type: documentation, automerge

#900 fix: coefficient computation during FermionicOp.simplify
  qiskit_nature/second_q/operators/fermionic_op.py
  test/second_q/operators/test_fermionic_op.py
Labels: automerge

#899 feat: make tensor_ordering utilities more configurable
  qiskit_nature/second_q/algorithms/initial_points/mp2_initial_point.py
  qiskit_nature/second_q/formats/fcidump/fcidump.py
  qiskit_nature/second_q/operators/electronic_integrals.py
  qiskit_nature/second_q/operators/tensor_ordering.py
  qiskit_nature/second_q/properties/angular_momentum.py
  test/second_q/operators/test_tensor_ordering.py
Labels: automerge

#877 fix GaussianForcesDriver.from_molecule improvements #400
  qiskit_nature/second_q/drivers/gaussiand/gaussian_forces_driver.py
  releasenotes/notes/fix-gaussian-forces-driver-from-molecule-xcf-6702ec346d1d94da.yaml
  test/second_q/drivers/gaussiand/test_driver_gaussian_forces.py
Labels: automerge

#858 Added `commutators`
  .pylintdict
  docs/apidocs/qiskit_nature.second_q.operators.commutators.rst
  qiskit_nature/second_q/operators/__init__.py
  qiskit_nature/second_q/operators/commutators.py
  qiskit_nature/second_q/operators/sparse_label_op.py
  test/second_q/operators/test_commutators.py
  test/second_q/operators/test_sparse_label_op.py
Labels: automerge

#906 fix: make PolynomialTensor method names consistent
  qiskit_nature/second_q/operators/polynomial_tensor.py
  test/second_q/operators/test_polynomial_tensor.py
Labels: automerge

#907 refactor: update API to kwargs-only where sensible
  qiskit_nature/second_q/algorithms/excited_states_solvers/excited_states_eigensolver.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/ground_state_eigensolver.py
  qiskit_nature/second_q/algorithms/initial_points/mp2_initial_point.py
  qiskit_nature/second_q/circuit/library/bogoliubov_transform.py
  qiskit_nature/second_q/drivers/gaussiand/gaussian_forces_driver.py
  qiskit_nature/second_q/drivers/gaussiand/gaussian_log_result.py
  qiskit_nature/second_q/hamiltonians/lattices/hyper_cubic_lattice.py
  qiskit_nature/second_q/hamiltonians/lattices/lattice.py
  qiskit_nature/second_q/hamiltonians/lattices/triangular_lattice.py
  qiskit_nature/second_q/hamiltonians/quadratic_hamiltonian.py
  qiskit_nature/second_q/hamiltonians/vibrational_energy.py
  qiskit_nature/second_q/mappers/logarithmic_mapper.py
  qiskit_nature/second_q/mappers/qubit_converter.py
  qiskit_nature/second_q/operators/fermionic_op.py
  qiskit_nature/second_q/operators/sparse_label_op.py
  qiskit_nature/second_q/problems/vibrational_structure_problem.py
  test/second_q/circuit/library/ansatzes/test_ucc.py
  test/second_q/mappers/test_logarithmic_mapper.py
  test/second_q/mappers/test_qubit_converter.py
  test/second_q/operators/test_sparse_label_op.py
Labels: automerge

#904 Added `round()` function to `SparseLabelOp`
  qiskit_nature/second_q/operators/sparse_label_op.py
  test/second_q/operators/test_sparse_label_op.py
Labels: automerge

#890 make QuadraticHamiltonian a subclass of PolynomialTensor
  qiskit_nature/second_q/hamiltonians/quadratic_hamiltonian.py
  qiskit_nature/second_q/operators/sparse_label_op.py
  test/second_q/hamiltonians/test_quadratic_hamiltonian.py
Labels: automerge

#913 fix: problem attribute propagation in transformers
  qiskit_nature/second_q/problems/electronic_structure_problem.py
  qiskit_nature/second_q/transformers/active_space_transformer.py
  qiskit_nature/second_q/transformers/basis_transformer.py
  test/second_q/transformers/test_active_space_transformer.py
  test/second_q/transformers/test_basis_transformer.py
Labels: automerge

#916 Fix CI PSI4 Windows install
  .github/actions/install-psi4/action.yml
Labels: priority: critical, automerge, type: ci

#914 fix: ElectronicEnergy.fock should be one-body term
  qiskit_nature/second_q/hamiltonians/electronic_energy.py
  test/second_q/hamiltonians/test_electronic_energy.py
Labels: automerge

#903 Implements `HartreeFock` and `VSCF` initial states as a `BlueprintCircuit`
  qiskit_nature/second_q/circuit/library/initial_states/hartree_fock.py
  qiskit_nature/second_q/circuit/library/initial_states/vscf.py
  releasenotes/notes/feat-vscf-and-hartree-as-blueprintcircuits-15167723fdd504d5.yaml
  test/second_q/circuit/library/initial_states/test_hartree_fock.py
  test/second_q/circuit/library/initial_states/test_vscf.py
Labels: automerge
