Repository qiskit-community/qiskit-nature, pull requests merged in 2022-11, with the labels that each got.

#923 docs: temporarily disable intersphinx integration with SciPy
  docs/conf.py
Labels: priority: critical, type: ci

#922 Docs Review Initial Pass
  docs/apidocs/qiskit_nature.logging.rst
  docs/apidocs/qiskit_nature.second_q.algorithms.initial_points.rst
  docs/apidocs/qiskit_nature.second_q.algorithms.rst
  docs/apidocs/qiskit_nature.second_q.circuit.library.ansatzes.utils.rst
  docs/apidocs/qiskit_nature.second_q.circuit.library.rst
  docs/apidocs/qiskit_nature.second_q.circuit.rst
  docs/apidocs/qiskit_nature.second_q.drivers.gaussiand.rst
  docs/apidocs/qiskit_nature.second_q.drivers.psi4d.rst
  docs/apidocs/qiskit_nature.second_q.drivers.pyscfd.rst
  docs/apidocs/qiskit_nature.second_q.drivers.rst
  docs/apidocs/qiskit_nature.second_q.formats.fcidump.rst
  docs/apidocs/qiskit_nature.second_q.formats.qcschema.rst
  docs/apidocs/qiskit_nature.second_q.formats.rst
  docs/apidocs/qiskit_nature.second_q.hamiltonians.lattices.rst
  docs/apidocs/qiskit_nature.second_q.hamiltonians.rst
  docs/apidocs/qiskit_nature.second_q.mappers.rst
  docs/apidocs/qiskit_nature.second_q.operators.commutators.rst
  docs/apidocs/qiskit_nature.second_q.operators.rst
  docs/apidocs/qiskit_nature.second_q.operators.tensor_ordering.rst
  docs/apidocs/qiskit_nature.second_q.problems.rst
  docs/apidocs/qiskit_nature.second_q.properties.rst
  docs/apidocs/qiskit_nature.second_q.rst
  docs/apidocs/qiskit_nature.second_q.transformers.rst
  docs/apidocs/qiskit_nature.settings.rst
  docs/apidocs/qiskit_nature.utils.rst
  docs/conf.py
  qiskit_nature/second_q/__init__.py
  qiskit_nature/second_q/algorithms/__init__.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/__init__.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/eigensolver_factories/__init__.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/__init__.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/minimum_eigensolver_factories/__init__.py
  qiskit_nature/second_q/circuit/__init__.py
  qiskit_nature/second_q/circuit/library/__init__.py
  qiskit_nature/second_q/drivers/__init__.py
  qiskit_nature/second_q/formats/__init__.py
  qiskit_nature/second_q/formats/fcidump/__init__.py
  qiskit_nature/second_q/formats/qcschema/__init__.py
  qiskit_nature/second_q/hamiltonians/__init__.py
  qiskit_nature/second_q/hamiltonians/lattices/__init__.py
  qiskit_nature/second_q/operators/__init__.py
  qiskit_nature/second_q/problems/__init__.py
  qiskit_nature/second_q/properties/__init__.py
Labels: type: documentation

#926 Some docs updates
  .pylintdict
  docs/conf.py
  qiskit_nature/second_q/drivers/gaussiand/gaussian_forces_driver.py
  qiskit_nature/second_q/drivers/gaussiand/gaussiandriver.py
  qiskit_nature/second_q/drivers/psi4d/psi4driver.py
  qiskit_nature/second_q/drivers/pyscfd/pyscfdriver.py
  qiskit_nature/second_q/formats/fcidump/fcidump.py
  qiskit_nature/second_q/problems/base_problem.py
  qiskit_nature/second_q/problems/eigenstate_result.py
  qiskit_nature/second_q/problems/electronic_structure_problem.py
  qiskit_nature/second_q/problems/lattice_model_problem.py
  qiskit_nature/second_q/properties/angular_momentum.py
  qiskit_nature/second_q/properties/dipole_moment.py
  qiskit_nature/second_q/properties/magnetization.py
  qiskit_nature/second_q/properties/particle_number.py
Labels: type: documentation, automerge

#924 Fixed styles for transformers docs
  qiskit_nature/second_q/transformers/active_space_transformer.py
  qiskit_nature/second_q/transformers/freeze_core_transformer.py
Labels: type: documentation

#930 delete getitem and iter from ElectronicIntegrals
  qiskit_nature/second_q/operators/electronic_integrals.py
  qiskit_nature/second_q/transformers/active_space_transformer.py
  test/second_q/operators/test_electronic_integrals.py
Labels: automerge

#928 doc fixes in operators module
  qiskit_nature/second_q/operators/electronic_integrals.py
  qiskit_nature/second_q/operators/fermionic_op.py
  qiskit_nature/second_q/operators/polynomial_tensor.py
  qiskit_nature/second_q/operators/sparse_label_op.py
  qiskit_nature/second_q/operators/tensor_ordering.py
  qiskit_nature/second_q/operators/vibrational_op.py
Labels: type: documentation, automerge

#935 Deprecate module hdf5
  docs/apidocs/qiskit_nature.hdf5.rst
  qiskit_nature/__init__.py
  qiskit_nature/hdf5.py
  test/test_hdf5.py
Labels: type: documentation, automerge

#936 Remove sphinx_rtd_theme from CI
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: automerge, type: ci

#925 Reviewed and fixed `mapper` docs
  qiskit_nature/second_q/mappers/bksf.py
  qiskit_nature/second_q/mappers/direct_mapper.py
  qiskit_nature/second_q/mappers/logarithmic_mapper.py
  qiskit_nature/second_q/mappers/parity_mapper.py
Labels: type: documentation, automerge

#927 Review docs for `circuit` and `hamiltonians`
  .pylintdict
  qiskit_nature/second_q/circuit/library/ansatzes/chc.py
  qiskit_nature/second_q/circuit/library/ansatzes/puccd.py
  qiskit_nature/second_q/circuit/library/ansatzes/succd.py
  qiskit_nature/second_q/circuit/library/ansatzes/ucc.py
  qiskit_nature/second_q/circuit/library/ansatzes/uccsd.py
  qiskit_nature/second_q/circuit/library/ansatzes/uvcc.py
  qiskit_nature/second_q/circuit/library/ansatzes/uvccsd.py
  qiskit_nature/second_q/circuit/library/bogoliubov_transform.py
  qiskit_nature/second_q/circuit/library/initial_states/fermionic_gaussian_state.py
  qiskit_nature/second_q/circuit/library/initial_states/hartree_fock.py
  qiskit_nature/second_q/circuit/library/initial_states/slater_determinant.py
  qiskit_nature/second_q/hamiltonians/electronic_energy.py
  qiskit_nature/second_q/hamiltonians/fermi_hubbard_model.py
  qiskit_nature/second_q/hamiltonians/heisenberg_model.py
  qiskit_nature/second_q/hamiltonians/ising_model.py
  qiskit_nature/second_q/hamiltonians/lattice_model.py
  qiskit_nature/second_q/hamiltonians/lattices/boundary_condition.py
  qiskit_nature/second_q/hamiltonians/lattices/hyper_cubic_lattice.py
  qiskit_nature/second_q/hamiltonians/lattices/lattice.py
  qiskit_nature/second_q/hamiltonians/lattices/line_lattice.py
  qiskit_nature/second_q/hamiltonians/lattices/square_lattice.py
  qiskit_nature/second_q/hamiltonians/quadratic_hamiltonian.py
  qiskit_nature/second_q/hamiltonians/vibrational_energy.py
  qiskit_nature/second_q/mappers/qubit_converter.py
Labels: type: documentation, automerge

#934 Algorithms docs improvements.
  qiskit_nature/second_q/algorithms/__init__.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/eigensolver_factories/eigensolver_factory.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/eigensolver_factories/numpy_eigensolver_factory.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/excited_states_eigensolver.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/excited_states_solver.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom_electronic_ops_builder.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom_vibrational_ops_builder.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/ground_state_eigensolver.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/ground_state_solver.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/minimum_eigensolver_factories/minimum_eigensolver_factory.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/minimum_eigensolver_factories/numpy_minimum_eigensolver_factory.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_ucc_factory.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_uvcc_factory.py
  qiskit_nature/second_q/algorithms/initial_points/__init__.py
  qiskit_nature/second_q/algorithms/initial_points/hf_initial_point.py
  qiskit_nature/second_q/algorithms/initial_points/initial_point.py
  qiskit_nature/second_q/algorithms/initial_points/mp2_initial_point.py
  qiskit_nature/second_q/algorithms/initial_points/vscf_initial_point.py
Labels: type: documentation, automerge

#937 refactor: remove `SecondQuantizedOp`
  qiskit_nature/second_q/algorithms/excited_states_solvers/excited_states_eigensolver.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/excited_states_solver.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/ground_state_eigensolver.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/ground_state_solver.py
  qiskit_nature/second_q/circuit/library/ansatzes/ucc.py
  qiskit_nature/second_q/circuit/library/ansatzes/uvcc.py
  qiskit_nature/second_q/hamiltonians/hamiltonian.py
  qiskit_nature/second_q/mappers/qubit_converter.py
  qiskit_nature/second_q/mappers/qubit_mapper.py
  qiskit_nature/second_q/operators/__init__.py
  qiskit_nature/second_q/operators/second_quantized_op.py
  qiskit_nature/second_q/problems/base_problem.py
  releasenotes/notes/approx-eq-15521c2b1ece996b.yaml
  releasenotes/notes/is-hermitian-33d1000779fba472.yaml
  releasenotes/notes/op-norm-3f4d73df98bc03fc.yaml
  test/second_q/operators/utils.py
  test/second_q/problems/test_lattice_model_problem.py
Labels: automerge

#941 Post Release Process
  .github/workflows/deploy-docs.yml
  .mergify.yml
  qiskit_nature/VERSION.txt
Labels: automerge

#943 Fix release note formatting
  releasenotes/notes/0.5/0.5-prelude-a1d20e9b76893ece.yaml
Labels: stable backport potential, type: documentation

#942 Fix deployment of translatable strings
  .github/workflows/deploy-docs.yml
  tox.ini
Labels: automerge, type: ci

#946 [Stable] Fix release note formatting (#943)
  releasenotes/notes/0.5/0.5-prelude-a1d20e9b76893ece.yaml
Labels: type: documentation

#947 Show updated release notes
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  tox.ini
Labels: type: documentation

#960 Ignore untagged reno notes on documentation & Fix CI Pyquante2 windows install
  .github/actions/install-psi4/action.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  tools/ignore_untagged_notes.sh
Labels: type: ci

#963 Support latest mypy, add gaussian libraries to wheel file
  MANIFEST.in
  qiskit_nature/second_q/algorithms/ground_state_solvers/ground_state_eigensolver.py
  releasenotes/notes/gaussian-wheel-5f608294891f76ce.yaml
  requirements-dev.txt
Labels: automerge, type: ci

#970 remove ENHANCEMENT_REQUEST issue template
  .github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST.yaml
Labels: automerge

#966 Remove negative coeff. from `SpinOp.index_order`
  qiskit_nature/second_q/operators/spin_op.py
  releasenotes/notes/fix-spin-op-index-order-024e76d21b08bb9a.yaml
  test/second_q/operators/test_spin_op.py
Labels: automerge, stable backport potential

#975 Fix #953
  qiskit_nature/second_q/operators/sparse_label_op.py
  releasenotes/notes/fix-sparse-label-op-numpy-type-support-759a10226357157c.yaml
  test/second_q/operators/test_sparse_label_op.py
Labels: automerge, stable backport potential

#979 Update docs to use new sphinx theme
  .github/workflows/main.yml
  docs/_templates/layout.html
  docs/conf.py
  requirements-dev.txt
Labels: type: documentation, type: enhancement, automerge, stable backport potential

#981 Simplify pyscf installation check
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  docs/conf.py
  qiskit_nature/optionals.py
  qiskit_nature/second_q/drivers/pyscfd/pyscfdriver.py
Labels: type: bug, type: ci, stable backport potential

#964 Leverage opt_einsum for sparse-einsum support
  .github/actions/install-nature/action.yml
  .github/workflows/main.yml
  qiskit_nature/optionals.py
  qiskit_nature/second_q/algorithms/initial_points/mp2_initial_point.py
  qiskit_nature/second_q/drivers/gaussiand/gaussiandriver.py
  qiskit_nature/second_q/drivers/pyscfd/pyscfdriver.py
  qiskit_nature/second_q/operators/polynomial_tensor.py
  qiskit_nature/utils/__init__.py
  qiskit_nature/utils/opt_einsum.py
  releasenotes/notes/opt_einsum-f267e198d895f801.yaml
  setup.py
  test/second_q/operators/test_polynomial_tensor.py
Labels: type: enhancement

#983 create testing module and move random.py in there
  docs/apidocs/qiskit_nature.testing.rst
  qiskit_nature/__init__.py
  qiskit_nature/testing/__init__.py
  qiskit_nature/testing/random.py
  releasenotes/notes/testing-module-d0f545c685574af2.yaml
  test/circuit/library/initial_states/test_fermionic_gaussian_state.py
  test/circuit/library/initial_states/test_slater_determinant.py
  test/circuit/library/test_bogoliubov_transform.py
  test/operators/second_quantization/test_quadratic_hamiltonian.py
  test/second_q/circuit/library/initial_states/test_fermionic_gaussian_state.py
  test/second_q/circuit/library/initial_states/test_slater_determinant.py
  test/second_q/circuit/library/test_bogoliubov_transform.py
  test/second_q/hamiltonians/test_quadratic_hamiltonian.py
Labels: automerge
