Repository qiskit-community/qiskit-nature, pull requests merged in 2022-01, with the labels that each got.

#490 Fix mypy errors created with latest numpy
  qiskit_nature/algorithms/excited_states_solvers/qeom.py
  qiskit_nature/algorithms/pes_samplers/extrapolator.py
  qiskit_nature/algorithms/pes_samplers/potentials/harmonic_potential.py
  qiskit_nature/drivers/molecule.py
  qiskit_nature/operators/second_quantization/spin_op.py
Labels: priority: high, stable backport potential, type: bug, type: ci

#488 Revert "Pin sphinxcontrib-spelling due to bug on latest version (#486)"
  requirements-dev.txt
Labels: stable backport potential, type: enhancement, automerge, type: ci

#475 Fix occupation computation of non-singlet states
  qiskit_nature/properties/second_quantization/electronic/particle_number.py
  releasenotes/notes/fix-non-singlet-occupation-computation-f2ff44b144b53732.yaml
  test/properties/second_quantization/electronic/test_particle_number.py
Labels: Changelog: Bugfix, stable backport potential

#495 Fix copyright
  qiskit_nature/properties/second_quantization/electronic/particle_number.py
  test/properties/second_quantization/electronic/test_particle_number.py
Labels: priority: critical

#478 Improve problem attribute access errors
  qiskit_nature/problems/second_quantization/electronic/electronic_structure_problem.py
Labels: Changelog: Bugfix, stable backport potential

#497 Pin sphinx-autodoc-typehints to unblock docs builds
  requirements-dev.txt
Labels: priority: high, stable backport potential, type: bug, automerge, type: ci

#476 Fix the units of the Molecule geometry
  qiskit_nature/drivers/second_quantization/pyscfd/pyscfdriver.py
  qiskit_nature/properties/second_quantization/electronic/electronic_structure_driver_result.py
  releasenotes/notes/fix-molecule-coordinate-units-61f109372dcf7842.yaml
  test/drivers/second_quantization/test_driver.py
Labels: Changelog: Bugfix, stable backport potential, automerge

#501 Fix copyright year check when rebasing
  tools/check_copyright.py
Labels: stable backport potential, type: bug, automerge, type: ci

#503 fix: update BlueprintCircuit derivatives
  qiskit_nature/circuit/library/ansatzes/chc.py
  qiskit_nature/circuit/library/ansatzes/ucc.py
  qiskit_nature/circuit/library/ansatzes/uvcc.py
Labels: priority: critical

#504 Bump Terra requirements
  requirements.txt
Labels: priority: critical, automerge

#509 Fix VQE unit test
  test/algorithms/pes_samplers/test_bopes_sampler.py
Labels: priority: high, type: bug, automerge

#513 Add support for Python 3.10
  .github/workflows/main.yml
  pyproject.toml
  qiskit_nature/drivers/gaussiand/gauopen/qcmatrixio.cp310-win_amd64.pyd
  qiskit_nature/drivers/gaussiand/gauopen/qcmatrixio.cp39-win_amd64.pyd
  qiskit_nature/drivers/gaussiand/gauopen/qcmatrixio.cpython-310-darwin.so
  qiskit_nature/drivers/gaussiand/gauopen/qcmatrixio.cpython-310-x86_64-linux-gnu.so
  qiskit_nature/drivers/gaussiand/gauopen/qcmatrixio.cpython-39-darwin.so
  qiskit_nature/drivers/gaussiand/gauopen/qcmatrixio.cpython-39-x86_64-linux-gnu.so
  qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cp310-win_amd64.pyd
  qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cpython-310-darwin.so
  qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cpython-310-x86_64-linux-gnu.so
  releasenotes/notes/add-python310-support-6ef188b2e1572cc8.yaml
  setup.py
  tox.ini
Labels: type: enhancement

#517 Pin Windows CI version to 2019
  .github/actions/install-main-dependencies/action.yml
  .github/actions/install-psi4/action.yml
  .github/workflows/main.yml
Labels: priority: high, type: ci

#516 Pylint: enabled useless suppression warning
  .pylintrc
  qiskit_nature/algorithms/excited_states_solvers/qeom.py
  qiskit_nature/circuit/library/ansatzes/chc.py
  qiskit_nature/drivers/bosonic_bases/harmonic_basis.py
  qiskit_nature/drivers/fcidumpd/dumper.py
  qiskit_nature/drivers/fcidumpd/parser.py
  qiskit_nature/drivers/pyquanted/integrals.py
  qiskit_nature/drivers/pyquanted/pyquantedriver.py
  qiskit_nature/drivers/pyscfd/integrals.py
  qiskit_nature/drivers/pyscfd/pyscfdriver.py
  qiskit_nature/drivers/qmolecule.py
  qiskit_nature/drivers/second_quantization/fcidumpd/dumper.py
  qiskit_nature/drivers/second_quantization/fcidumpd/fcidumpdriver.py
  qiskit_nature/drivers/second_quantization/fcidumpd/parser.py
  qiskit_nature/drivers/second_quantization/pyquanted/integrals.py
  qiskit_nature/drivers/second_quantization/pyquanted/pyquantedriver.py
  qiskit_nature/drivers/second_quantization/pyscfd/pyscfdriver.py
  qiskit_nature/mappers/second_quantization/bravyi_kitaev_mapper.py
  qiskit_nature/problems/sampling/protein_folding/bead_distances/distance_map_builder.py
  qiskit_nature/properties/second_quantization/electronic/bases/electronic_basis.py
  qiskit_nature/transformers/second_quantization/electronic/freeze_core_transformer.py
  test/algorithms/ground_state_solvers/test_adapt_vqe.py
  test/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
  test/test_readme_sample.py
  test/transformers/second_quantization/electronic/test_active_space_transformer.py
  test/transformers/second_quantization/electronic/test_freeze_core_transformer.py
Labels: automerge
