Repository qiskit-community/qiskit-nature, pull requests merged in 2023-04, with the labels that each got.

#1109 Various small updates for docs and docs CI
  .github/workflows/main.yml
  .pylintdict
  docs/conf.py
  requirements-dev.txt
  tox.ini
Labels: type: documentation, type: ci

#1111 Fix the behavior of `SparseLabelOp.is_zero` for parameterized operators
  qiskit_nature/second_q/operators/sparse_label_op.py
  releasenotes/notes/fix-sparse-label-op-is-zero-ebeca4d6871c9642.yaml
  test/second_q/operators/test_sparse_label_op.py
Labels: automerge

#1092 Clean up deprecation warnings in CI
  qiskit_nature/drivers/second_quantization/hdf5d/hdf5driver.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom.py
  qiskit_nature/second_q/circuit/library/initial_states/hartree_fock.py
  qiskit_nature/second_q/formats/watson/watson_hamiltonian.py
  qiskit_nature/second_q/operators/tensor.py
  qiskit_nature/second_q/problems/electronic_structure_problem.py
  test/second_q/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
  test/second_q/algorithms/ground_state_solvers/test_groundstate_eigensolver_mapper.py
  test/second_q/circuit/library/ansatzes/test_ucc.py
  test/second_q/circuit/library/initial_states/test_hartree_fock.py
  test/second_q/circuit/library/initial_states/test_vscf.py
  test/second_q/mappers/test_qubit_converter.py
  test/second_q/mappers/test_tapered_qubit_mapper.py
  test/second_q/problems/test_electronic_structure_problem.py
Labels: automerge

#939 Add support for Python 3.11
  .github/workflows/main.yml
  .pylintrc
  constraints.txt
  pyproject.toml
  qiskit_nature/circuit/library/ansatzes/ucc.py
  qiskit_nature/circuit/library/ansatzes/uvcc.py
  qiskit_nature/second_q/circuit/library/ansatzes/ucc.py
  qiskit_nature/second_q/circuit/library/ansatzes/uvcc.py
  qiskit_nature/second_q/drivers/gaussiand/gauopen/qcmatrixio.cp311-win_amd64.pyd
  qiskit_nature/second_q/drivers/gaussiand/gauopen/qcmatrixio.cpython-311-darwin.so
  qiskit_nature/second_q/drivers/gaussiand/gauopen/qcmatrixio.cpython-311-x86_64-linux-gnu.so
  qiskit_nature/second_q/drivers/gaussiand/gaussian_log_result.py
  qiskit_nature/second_q/operators/sparse_label_op.py
  releasenotes/notes/add-python311-support-3a939c4697ecd896.yaml
  requirements-dev.txt
  setup.py
  test/drivers/second_quantization/fcidumpd/test_driver_fcidump.py
  test/drivers/second_quantization/fcidumpd/test_driver_fcidump_dumper.py
  test/drivers/second_quantization/test_driver.py
  test/second_q/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
  test/second_q/algorithms/ground_state_solvers/test_groundstate_eigensolver_mapper.py
  test/second_q/drivers/test_driver.py
  test/second_q/formats/fcidump/test_fcidump.py
  test/second_q/formats/fcidump/test_fcidump_dumper.py
  test/second_q/operators/tensor_test_cases.py
  test/second_q/operators/test_symmetric_two_body.py
  tools/check_copyright.py
  tox.ini
Labels: type: enhancement

#1122 Extract code example from README into docs
  README.md
  docs/getting_started.rst
  qiskit_nature/second_q/problems/eigenstate_result.py
  qiskit_nature/second_q/problems/electronic_structure_result.py
  qiskit_nature/second_q/problems/lattice_model_result.py
  qiskit_nature/second_q/problems/vibrational_structure_result.py
  releasenotes/notes/result-formatting-precision-d62a868cbd801a58.yaml
  test/second_q/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
  test/second_q/algorithms/ground_state_solvers/test_groundstate_eigensolver_mapper.py
  test/second_q/problems/test_electronic_structure_result.py
Labels: on hold

#1127 Update citation
  CITATION.cff
  README.md
  docs/index.rst
Labels: stable backport potential

#1130 fix: performance of QubitMapper.map
  qiskit_nature/second_q/mappers/qubit_mapper.py
  releasenotes/notes/qubit-mapper-performance-ef339b83f951e5a3.yaml
Labels: stable backport potential

#1131 fix: formatting of ElectronicStructureResult
  qiskit_nature/second_q/problems/electronic_structure_result.py
  releasenotes/notes/fix-electronic-structure-result-printing-6e0b092097386c8f.yaml
Labels: automerge, stable backport potential

#1135 Fix lint after opflow deprecation
  qiskit_nature/operators/second_quantization/second_quantized_op.py
Labels: stable backport potential

#1138 Fix Mac CI PSI4 to 1.6
  .github/actions/install-psi4/action.yml
Labels: automerge, type: ci, stable backport potential

#1140 Update intersphinx mappings
  docs/conf.py
Labels: type: documentation, stable backport potential

#455 Include the option for imaginary parts in the UCC ansatz
  qiskit_nature/second_q/circuit/library/ansatzes/puccd.py
  qiskit_nature/second_q/circuit/library/ansatzes/ucc.py
  qiskit_nature/second_q/circuit/library/ansatzes/uccsd.py
  releasenotes/notes/ucc_imaginary-8d7d9c3322899a34.yaml
  test/second_q/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
  test/second_q/algorithms/ground_state_solvers/test_groundstate_eigensolver_mapper.py
  test/second_q/circuit/library/ansatzes/test_puccd.py
  test/second_q/circuit/library/ansatzes/test_uccsd.py
Labels: Changelog: New Feature
