Repository qiskit-community/qiskit-nature, pull requests merged in 2023-02, with the labels that each got.

#1031 Implementing the `TaperedQubitMapper`
  .pylintdict
  qiskit_nature/second_q/algorithms/excited_states_solvers/excited_states_eigensolver.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom_electronic_ops_builder.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom_vibrational_ops_builder.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/ground_state_eigensolver.py
  qiskit_nature/second_q/circuit/library/ansatzes/ucc.py
  qiskit_nature/second_q/circuit/library/ansatzes/uvcc.py
  qiskit_nature/second_q/circuit/library/initial_states/hartree_fock.py
  qiskit_nature/second_q/circuit/library/initial_states/vscf.py
  qiskit_nature/second_q/mappers/__init__.py
  qiskit_nature/second_q/mappers/qubit_converter.py
  qiskit_nature/second_q/mappers/qubit_mapper.py
  qiskit_nature/second_q/mappers/tapered_qubit_mapper.py
  qiskit_nature/second_q/problems/base_problem.py
  qiskit_nature/second_q/problems/electronic_structure_problem.py
  releasenotes/notes/add-get-tapered-mapper-for-problems-33292452930141d1.yaml
  test/second_q/algorithms/excited_state_solvers/test_excited_states_solvers.py
  test/second_q/algorithms/excited_state_solvers/test_excited_states_solvers_auxiliaries.py
  test/second_q/algorithms/excited_state_solvers/test_qeom_electronic_ops.py
  test/second_q/algorithms/excited_state_solvers/test_qeom_vibrational_ops.py
  test/second_q/algorithms/ground_state_solvers/test_groundstate_eigensolver_mapper.py
  test/second_q/circuit/library/initial_states/test_hartree_fock_mapper.py
  test/second_q/circuit/library/initial_states/test_vscf.py
  test/second_q/mappers/test_qubit_converter.py
  test/second_q/mappers/test_tapered_qubit_mapper.py
  test/second_q/problems/test_electronic_structure_problem.py
Labels: run_slow

#1051 Exclude site-packages from sphinx for tox runs
  docs/conf.py
  tools/ignore_untagged_notes.sh
Labels: type: documentation, stable backport potential

#1053 Install sparse on gettext tox
  tox.ini
Labels: type: documentation

#1037 Add missing QEOMResult docs
  .pylintdict
  qiskit_nature/second_q/algorithms/__init__.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/__init__.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom.py
  releasenotes/notes/pending-deprecate-mqwv-matrix-setter-1cd9e2dfb68d1a85.yaml
Labels: automerge

#1057 fix: printing debye-dipole-moment
  qiskit_nature/second_q/problems/electronic_structure_result.py
  releasenotes/notes/fix-debye-dipole-0154e964da22910d.yaml
  test/second_q/problems/test_electronic_structure_result.py
Labels: Community PR

#1033 Implement the `Tensor` class
  .pylintdict
  qiskit_nature/second_q/hamiltonians/lattices/hyper_cubic_lattice.py
  qiskit_nature/second_q/operators/__init__.py
  qiskit_nature/second_q/operators/electronic_integrals.py
  qiskit_nature/second_q/operators/fermionic_op.py
  qiskit_nature/second_q/operators/polynomial_tensor.py
  qiskit_nature/second_q/operators/spin_op.py
  qiskit_nature/second_q/operators/tensor.py
  qiskit_nature/second_q/operators/vibrational_op.py
  qiskit_nature/settings.py
  releasenotes/notes/feat-tensor-class-2ad38ba7246ccbd5.yaml
  test/second_q/hamiltonians/test_quadratic_hamiltonian.py
  test/second_q/operators/tensor_test_cases.py
  test/second_q/operators/test_fermionic_op.py
  test/second_q/operators/test_polynomial_tensor.py
  test/second_q/operators/test_tensor.py
Labels: automerge

#1043 feat: implements standalone usage of the ActiveSpaceTransformer
  qiskit_nature/second_q/problems/electronic_structure_problem.py
  qiskit_nature/second_q/transformers/active_space_transformer.py
  qiskit_nature/second_q/transformers/freeze_core_transformer.py
  releasenotes/notes/feat-standalone-active-space-9033186e6849f46d.yaml
  test/second_q/transformers/test_active_space_transformer.py
  test/second_q/transformers/test_freeze_core_transformer.py
Labels: automerge

#1062 Fix tutorial thumbnails
  docs/conf.py
Labels: type: documentation, automerge, stable backport potential

#1064 Update deploy docs workflow
  .github/workflows/deploy-docs.yml
Labels: type: ci, stable backport potential

#1068 Fixing Typo on Line 54
  docs/migration/00_Migration_Guide_to_v0.5.ipynb
  docs/migration/00a_Solving_problems_with_v0.5.ipynb
Labels: stable backport potential

#1050 Replace PauliSumOp with SparsePauliOp
  qiskit_nature/deprecation.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/excited_states_eigensolver.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/excited_states_solver.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom_electronic_ops_builder.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom_vibrational_ops_builder.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/ground_state_eigensolver.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/ground_state_solver.py
  qiskit_nature/second_q/circuit/library/ansatzes/ucc.py
  qiskit_nature/second_q/circuit/library/ansatzes/uvcc.py
  qiskit_nature/second_q/circuit/library/initial_states/hartree_fock.py
  qiskit_nature/second_q/circuit/library/initial_states/vscf.py
  qiskit_nature/second_q/mappers/bksf.py
  qiskit_nature/second_q/mappers/direct_mapper.py
  qiskit_nature/second_q/mappers/fermionic_mapper.py
  qiskit_nature/second_q/mappers/interleaved_qubit_mapper.py
  qiskit_nature/second_q/mappers/linear_mapper.py
  qiskit_nature/second_q/mappers/logarithmic_mapper.py
  qiskit_nature/second_q/mappers/parity_mapper.py
  qiskit_nature/second_q/mappers/qubit_converter.py
  qiskit_nature/second_q/mappers/qubit_mapper.py
  qiskit_nature/second_q/mappers/spin_mapper.py
  qiskit_nature/second_q/mappers/tapered_qubit_mapper.py
  qiskit_nature/second_q/mappers/vibrational_mapper.py
  qiskit_nature/settings.py
  releasenotes/notes/paulisumop-replace-d1ae54d1854b301b.yaml
  test/nature_test_case.py
  test/second_q/mappers/resources/reference_direct_mapper.py
  test/second_q/mappers/test_bksf_mapper.py
  test/second_q/mappers/test_bravyi_kitaev_mapper.py
  test/second_q/mappers/test_direct_mapper.py
  test/second_q/mappers/test_jordan_wigner_mapper.py
  test/second_q/mappers/test_linear_mapper.py
  test/second_q/mappers/test_logarithmic_mapper.py
  test/second_q/mappers/test_parity_mapper.py
  test/second_q/mappers/test_qubit_converter.py
  test/test_deprecation.py
Labels: automerge

#1073 `QubitConverter` deprecation
  .pylintdict
  qiskit_nature/deprecation.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/excited_states_eigensolver.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom_electronic_ops_builder.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom_vibrational_ops_builder.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/ground_state_eigensolver.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/ground_state_solver.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/minimum_eigensolver_factories/minimum_eigensolver_factory.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/minimum_eigensolver_factories/numpy_minimum_eigensolver_factory.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_ucc_factory.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_uvcc_factory.py
  qiskit_nature/second_q/circuit/library/ansatzes/puccd.py
  qiskit_nature/second_q/circuit/library/ansatzes/succd.py
  qiskit_nature/second_q/circuit/library/ansatzes/ucc.py
  qiskit_nature/second_q/circuit/library/ansatzes/uccsd.py
  qiskit_nature/second_q/circuit/library/ansatzes/uvcc.py
  qiskit_nature/second_q/circuit/library/ansatzes/uvccsd.py
  qiskit_nature/second_q/circuit/library/bogoliubov_transform.py
  qiskit_nature/second_q/circuit/library/initial_states/fermionic_gaussian_state.py
  qiskit_nature/second_q/circuit/library/initial_states/hartree_fock.py
  qiskit_nature/second_q/circuit/library/initial_states/slater_determinant.py
  qiskit_nature/second_q/circuit/library/initial_states/vscf.py
  qiskit_nature/second_q/mappers/interleaved_qubit_mapper.py
  qiskit_nature/second_q/mappers/qubit_converter.py
  qiskit_nature/second_q/mappers/qubit_mapper.py
  qiskit_nature/second_q/mappers/tapered_qubit_mapper.py
  qiskit_nature/second_q/problems/base_problem.py
  qiskit_nature/second_q/problems/electronic_structure_problem.py
  releasenotes/notes/deprecate-qubit-converter-313ee07a36aa0c71.yaml
  test/second_q/algorithms/excited_state_solvers/test_excited_states_solvers.py
  test/second_q/algorithms/excited_state_solvers/test_excited_states_solvers_auxiliaries.py
  test/second_q/algorithms/excited_state_solvers/test_qeom_electronic_ops.py
  test/second_q/algorithms/excited_state_solvers/test_qeom_vibrational_ops.py
  test/second_q/algorithms/ground_state_solvers/minimum_eigensolver_factories/test_vqe_ucc_factory.py
  test/second_q/algorithms/ground_state_solvers/minimum_eigensolver_factories/test_vqe_uvcc_factory.py
  test/second_q/algorithms/ground_state_solvers/test_advanced_ucc_variants.py
  test/second_q/algorithms/ground_state_solvers/test_swaprz.py
  test/second_q/algorithms/initial_points/test_mp2_initial_point.py
  test/second_q/circuit/library/ansatzes/test_puccd.py
  test/second_q/circuit/library/ansatzes/test_succd.py
  test/second_q/circuit/library/ansatzes/test_ucc.py
  test/second_q/circuit/library/ansatzes/test_uccsd.py
  test/second_q/circuit/library/ansatzes/test_uvcc.py
  test/second_q/circuit/library/initial_states/test_fermionic_gaussian_state.py
  test/second_q/circuit/library/initial_states/test_hartree_fock.py
  test/second_q/circuit/library/initial_states/test_hartree_fock_mapper.py
  test/second_q/circuit/library/initial_states/test_slater_determinant.py
  test/second_q/circuit/library/initial_states/test_vscf.py
  test/second_q/circuit/library/test_bogoliubov_transform.py
  test/second_q/hamiltonians/test_quadratic_hamiltonian.py
  test/second_q/mappers/test_bksf_mapper.py
  test/second_q/mappers/test_interleaved_qubit_mapper.py
  test/second_q/mappers/test_jordan_wigner_mapper.py
  test/second_q/mappers/test_parity_mapper.py
  test/second_q/mappers/test_qubit_converter.py
  test/second_q/mappers/test_tapered_qubit_mapper.py
  test/second_q/problems/test_electronic_structure_problem.py
  test/test_end2end_with_vqe.py
Labels: automerge
