Repository qiskit-community/qiskit-nature, pull requests merged in 2023-01, with the labels that each got.

#1015 Pending deprecate M,Q,W,V matrix setters in QEOMResult
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom.py
  releasenotes/notes/pending-deprecate-mqwv-matrix-setter-1cd9e2dfb68d1a85.yaml
Labels: automerge

#1016 Fix mypy warnings
  qiskit_nature/algorithms/initial_points/initial_point.py
  qiskit_nature/second_q/algorithms/initial_points/initial_point.py
  qiskit_nature/second_q/operators/_bits_container.py
  qiskit_nature/settings.py
  test/drivers/second_quantization/test_driver.py
  test/second_q/drivers/test_driver.py
  test/test_logging.py
Labels: automerge

#1014 Fix dtype bug in BogoliubovTransform
  qiskit_nature/second_q/circuit/library/bogoliubov_transform.py
  qiskit_nature/utils/linalg.py
  releasenotes/notes/givens-fix-a12cb547cf5a1be4.yaml
  test/second_q/circuit/library/test_bogoliubov_transform.py
Labels: automerge, stable backport potential

#1026 Fix copyright
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom_vibrational_ops_builder.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/minimum_eigensolver_factories/minimum_eigensolver_factory.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/minimum_eigensolver_factories/numpy_minimum_eigensolver_factory.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_ucc_factory.py
  qiskit_nature/second_q/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_uvcc_factory.py
  qiskit_nature/second_q/circuit/library/ansatzes/puccd.py
  qiskit_nature/second_q/circuit/library/ansatzes/succd.py
  qiskit_nature/second_q/circuit/library/ansatzes/uccsd.py
  qiskit_nature/second_q/circuit/library/ansatzes/uvcc.py
  qiskit_nature/second_q/circuit/library/ansatzes/uvccsd.py
  qiskit_nature/second_q/circuit/library/initial_states/fermionic_gaussian_state.py
  qiskit_nature/second_q/circuit/library/initial_states/hartree_fock.py
  qiskit_nature/second_q/circuit/library/initial_states/slater_determinant.py
  qiskit_nature/second_q/circuit/library/initial_states/vscf.py
  qiskit_nature/second_q/mappers/bksf.py
  qiskit_nature/second_q/mappers/bravyi_kitaev_mapper.py
  qiskit_nature/second_q/mappers/direct_mapper.py
  qiskit_nature/second_q/mappers/fermionic_mapper.py
  qiskit_nature/second_q/mappers/jordan_wigner_mapper.py
  qiskit_nature/second_q/mappers/linear_mapper.py
  qiskit_nature/second_q/mappers/logarithmic_mapper.py
  qiskit_nature/second_q/mappers/parity_mapper.py
  qiskit_nature/second_q/mappers/spin_mapper.py
  qiskit_nature/second_q/mappers/vibrational_mapper.py
  qiskit_nature/second_q/problems/base_problem.py
  qiskit_nature/second_q/problems/electronic_structure_problem.py
  test/second_q/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
  test/second_q/mappers/test_jordan_wigner_mapper.py
  test/second_q/mappers/test_qubit_converter.py
Labels: priority: critical

#1002 Added thumbnail images to tutorials gallery
  docs/_static/co2_vibration.png
  docs/_static/core-orbitals.png
  docs/_static/lattice_protein.png
  docs/_static/orbitals.png
  docs/_static/runtime.png
  docs/conf.py
  docs/tutorials/07_leveraging_qiskit_runtime.ipynb
  docs/tutorials/10_lattice_models.ipynb
  docs/tutorials/11_quadratic_hamiltonian_and_slater_determinants.ipynb
  docs/tutorials/12_deuteron_binding_energy.ipynb
  test/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
Labels: automerge

#1028 Fix #1025
  docs/tutorials/01_electronic_structure.ipynb
  docs/tutorials/06_qubit_mappers.ipynb
Labels: type: documentation, automerge, stable backport potential

#1035 Fix Aer build error in CI
  .github/actions/install-main-dependencies/action.yml
Labels: priority: critical, automerge, type: ci

#1018 Implements Two Qubit Reduction in ParityMapper
  .pylintdict
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom.py
  qiskit_nature/second_q/mappers/parity_mapper.py
  qiskit_nature/second_q/mappers/qubit_converter.py
  releasenotes/notes/implements-two-qubit-reduction-in-paritymapper-f88ef199f0a954b6.yaml
  test/second_q/algorithms/excited_state_solvers/test_excited_states_solvers.py
  test/second_q/mappers/test_parity_mapper.py
  test/second_q/mappers/test_qubit_converter.py
Labels: automerge

#1041 feat: additional ways to construct an `ElectronicDensity`
  .pylintdict
  qiskit_nature/second_q/properties/electronic_density.py
  releasenotes/notes/feat-electronic-denisty-initializations-d1bd5131c5776418.yaml
  test/second_q/properties/test_electronic_density.py
Labels: automerge

#1045 fix: enforce zero absolute tolerance in commutator routines
  qiskit_nature/second_q/operators/commutators.py
  releasenotes/notes/fix-commutator-simplification-tolerance-09c72ce1adc0bbf0.yaml
  test/second_q/operators/test_commutators.py
Labels: automerge

#1048 Pin setuptools to allow pre-releases on requirements.txt
  pyproject.toml
  requirements.txt
Labels: automerge

#1046 feat: implement the `InterleavedQubitMapper`
  qiskit_nature/second_q/mappers/__init__.py
  qiskit_nature/second_q/mappers/interleaved_qubit_mapper.py
  releasenotes/notes/feat-interleaved-qubit-mapper-1f04e5b12383386e.yaml
  test/second_q/mappers/test_interleaved_qubit_mapper.py
Labels: automerge
