Repository qiskit-community/qiskit-nature, pull requests merged in 2023-09, with the labels that each got.

#1230 Rotate poBranch deploy key
  tools/github_poBranch_update_key.enc
Labels: automerge, stable backport potential

#1227 Remove PyQuante2 from CI and optionals
  .github/workflows/main.yml
  qiskit_nature/optionals.py
Labels: automerge

#1027 Add `HexagonalLattice` Class
  qiskit_nature/second_q/hamiltonians/lattices/__init__.py
  qiskit_nature/second_q/hamiltonians/lattices/hexagonal_lattice.py
  releasenotes/notes/add-hexagonal-lattice-a981f1b5c832a154.yaml
  requirements.txt
  test/second_q/hamiltonians/lattices/test_hexagonal_lattice.py
Labels: automerge

#1236 Update Getting Started page
  docs/getting_started.rst
Labels: automerge

#1238 ci: test minimal Python version on Mac OS
  .github/workflows/main.yml
Labels: automerge, stable backport potential

#1229 Switch from qiskit-terra to qiskit
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/main.yml
  .github/workflows/neko.yml
  CONTRIBUTING.md
  README.md
  docs/index.rst
  qiskit_nature/second_q/circuit/library/ansatzes/ucc.py
  qiskit_nature/second_q/circuit/library/ansatzes/uvcc.py
  requirements.txt
  tox.ini
Labels: automerge

#1243 feat: use PySCF unfolding routines for performance
  qiskit_nature/second_q/operators/symmetric_two_body.py
  releasenotes/notes/faster-symmetry-unfolding-46d775eb5b2a4bf7.yaml
Labels: automerge

#1240 feat: improve the `SparseLabelOp.register_length` handling
  qiskit_nature/second_q/operators/bosonic_op.py
  qiskit_nature/second_q/operators/fermionic_op.py
  qiskit_nature/second_q/operators/sparse_label_op.py
  qiskit_nature/second_q/operators/spin_op.py
  qiskit_nature/second_q/operators/vibrational_op.py
  releasenotes/notes/improve-register-length-handling-cb55f644da136828.yaml
  test/second_q/operators/test_bosonic_op.py
  test/second_q/operators/test_fermionic_op.py
  test/second_q/operators/test_spin_op.py
  test/second_q/operators/test_vibrational_op.py
Labels: automerge

#1241 feat: implements the PUCCSD ansatz
  .pylintdict
  qiskit_nature/second_q/circuit/library/__init__.py
  qiskit_nature/second_q/circuit/library/ansatzes/__init__.py
  qiskit_nature/second_q/circuit/library/ansatzes/puccsd.py
  qiskit_nature/second_q/circuit/library/ansatzes/ucc.py
  releasenotes/notes/puccsd-ansatz-7c97be6dca32a873.yaml
  test/second_q/circuit/library/ansatzes/test_puccsd.py
Labels: automerge

#1246 Some minor CI updates
  .github/workflows/main.yml
Labels: type: ci

#1247 docs: refer to plugin integrations
  README.md
  docs/getting_started.rst
Labels: type: documentation, automerge

#1242 feat: support manual active space selection for unrestricted spin cases
  qiskit_nature/second_q/transformers/active_space_transformer.py
  qiskit_nature/second_q/transformers/freeze_core_transformer.py
  releasenotes/notes/manual-unrestricted-spin-active-space-2462e3a9b8a10a10.yaml
  test/second_q/transformers/test_active_space_transformer.py
Labels: automerge
