Repository qiskit-community/qiskit-nature, pull requests merged in 2023-03, with the labels that each got.

#1082 Updates hard-coded user names
  .github/CODEOWNERS
  .github/workflows/deploy-docs.yml
Labels: priority: high, automerge, type: ci, stable backport potential

#1086 [stable] Unpin setuptools
  pyproject.toml
  requirements-dev.txt
  requirements.txt
Labels: priority: high, automerge

#1088 Update slack invite link
  README.md
Labels: automerge

#1090 fix: compatibility with mypy==1.1.1
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/main.yml
  qiskit_nature/second_q/formats/qcschema/qc_base.py
Labels: priority: critical, type: ci

#1096 Remove unnecessary `html_theme_path` option
  docs/conf.py
Labels: type: documentation, automerge

#1105 Install jupyter for tutorials builds
  .github/workflows/main.yml
Labels: type: ci

#1103 deploy documentation in qiskit.org/ecosystem
  tools/deploy_documentation.sh
Labels: type: documentation, automerge, type: ci, stable backport potential
