Repository qiskit-community/qiskit-nature, pull requests merged in 2023-05, with the labels that each got.

#1145 Pin ipython
  constraints.txt
Labels: automerge, type: ci, stable backport potential

#1022 Add low rank linalg utils
  .pylintdict
  qiskit_nature/testing/__init__.py
  qiskit_nature/testing/random.py
  qiskit_nature/utils/__init__.py
  qiskit_nature/utils/linalg.py
  releasenotes/notes/low-rank-linalg-86da86096d6122d8.yaml
  test/testing/__init__.py
  test/testing/test_random.py
  test/utils/test_linalg.py
Labels: automerge

#1151 Fix docstring of ElectronicDipoleMoment
  qiskit_nature/second_q/properties/dipole_moment.py
Labels: type: documentation, automerge, stable backport potential

#1153 Enable sparse optional for 3.11
  releasenotes/notes/sparse-3_11-1538988547ff6dd6.yaml
  setup.py
Labels: automerge, stable backport potential

#1159 Terra main vs stable install switch
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/main.yml
Labels: automerge, stable backport potential

#1146 Use a coherent name for the problem
  docs/tutorials/03_ground_state_solvers.ipynb
Labels: automerge

#1163 Turn off CI for forks
  .github/workflows/main.yml
  .github/workflows/neko.yml
Labels: type: ci, stable backport potential

#1162 Fix language toggle for docs
  docs/_templates/page.html
  docs/_templates/versions.html
  docs/conf.py
  docs/versionutils.py
  requirements-dev.txt
  tox.ini
Labels: type: documentation, automerge, stable backport potential

#1170 fix: the integer rounding in the ActiveSpaceTransformer
  qiskit_nature/second_q/transformers/active_space_transformer.py
  releasenotes/notes/fix-active-space-integer-rounding-753ae77146610d9d.yaml
Labels: automerge, stable backport potential

#1171 fix: properly propagate the ElectronicStructureProblem.reference_energy
  qiskit_nature/second_q/problems/electronic_structure_problem.py
  releasenotes/notes/fix-hartree-fock-reference-energy-6c43c5fd68d83505.yaml
  test/second_q/problems/test_electronic_structure_problem.py
Labels: automerge, stable backport potential

#1085 Bosonic operators
  .pylintdict
  qiskit_nature/second_q/mappers/__init__.py
  qiskit_nature/second_q/mappers/bosonic_linear_mapper.py
  qiskit_nature/second_q/mappers/bosonic_mapper.py
  qiskit_nature/second_q/operators/__init__.py
  qiskit_nature/second_q/operators/bosonic_op.py
  releasenotes/notes/bosonic-operator-and-mapper-45bfde873f092681.yaml
  test/second_q/mappers/test_bosonic_linear_mapper.py
  test/second_q/operators/test_bosonic_op.py
Labels: automerge

#1175 Improve docs
  docs/_templates/autosummary/class.rst
  docs/_templates/autosummary/class_no_inherited_members.rst
  qiskit_nature/second_q/circuit/library/__init__.py
  qiskit_nature/second_q/mappers/__init__.py
  qiskit_nature/second_q/operators/symmetric_two_body.py
Labels: type: documentation, automerge, stable backport potential

#1180 Remove manual Table of Contents in favor of autogenerated Page Table of Contents
  docs/migration/0.5_b_solving_problems.rst
  docs/migration/0.5_c_electronic_structure.rst
  docs/migration/0.5_d_vibrational_structure.rst
  docs/migration/0.5_e_lattice_models.rst
Labels: type: documentation, stable backport potential

#1177 Upgrade to qiskit_sphinx_theme 1.12
  docs/_static/no_image.png
  docs/conf.py
  docs/custom_directives.py
  docs/getting_started.rst
  docs/versionutils.py
  pyproject.toml
  requirements-dev.txt
  tox.ini
Labels: type: documentation, automerge, stable backport potential

#1185 Add project urls to setup
  setup.py
Labels: automerge, stable backport potential
