Repository qiskit-community/qiskit-nature, pull requests merged in 2024-02, with the labels that each got.

#1317 Update upload/download-artifact actions versions
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/deploy-code.yml
  .github/workflows/main.yml
Labels: stable backport potential

#1325 Add slow_test as it's no longer part of Qiskit 1.0
  .pylintdict
  test/__init__.py
  test/decorators.py
  test/second_q/algorithms/ground_state_solvers/test_advanced_ucc_variants.py
  test/second_q/algorithms/ground_state_solvers/test_groundstate_eigensolver.py
  test/second_q/algorithms/ground_state_solvers/test_swaprz.py
  test/second_q/drivers/pyscfd/test_driver_methods_pyscf.py
Labels: stable backport potential

#1328 Update Qiskit parallel map usage and remove TextProgressBar
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom_electronic_ops_builder.py
  qiskit_nature/second_q/algorithms/excited_states_solvers/qeom_vibrational_ops_builder.py
  qiskit_nature/utils/__init__.py
Labels: stable backport potential

#1332 Remove qiskit.org links from release notes
  releasenotes/notes/0.5/0.5-prelude-a1d20e9b76893ece.yaml
  releasenotes/notes/0.5/deprecate-legacy-code-fe9db8a009b6f5d2.yaml
  releasenotes/notes/0.6/0.6-prelude-fbf9f7e6b1b910fa.yaml
  releasenotes/notes/0.7/0.7-prelude-169d294985170fd5.yaml
Labels: automerge

#1334 Remove all other languages other than Spanish and Japanese
  docs/conf.py
Labels: type: documentation, stable backport potential

#1336 Fix tutorials to work with Qiskit 1.0
  .github/workflows/deploy-docs.yml
  docs/tutorials/01_electronic_structure.ipynb
  docs/tutorials/02_vibrational_structure.ipynb
  docs/tutorials/03_ground_state_solvers.ipynb
  docs/tutorials/04_excited_states_solvers.ipynb
  docs/tutorials/05_problem_transformers.ipynb
  docs/tutorials/06_qubit_mappers.ipynb
  docs/tutorials/07_leveraging_qiskit_runtime.ipynb
  docs/tutorials/08_qcschema.ipynb
  docs/tutorials/09_properties.ipynb
  docs/tutorials/10_lattice_models.ipynb
  docs/tutorials/11_quadratic_hamiltonian_and_slater_determinants.ipynb
  docs/tutorials/12_deuteron_binding_energy.ipynb
  docs/tutorials/tutorial_magics.py
Labels: type: documentation, stable backport potential

#1338 Add Python 3.12 support
  .github/workflows/main.yml
  constraints.txt
  releasenotes/notes/py_3_12_support-ff91e3a300421b3d.yaml
  setup.py
  tox.ini
Labels: type: ci, stable backport potential

#1341 Revert Python 3.12.0 specific usage
  .github/workflows/main.yml
Labels: type: ci, stable backport potential
